<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Social/GetFriendDetailsMessage.proto

namespace POGOProtos\Networking\Requests\Social;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Social.GetFriendDetailsMessage</code>
 */
class GetFriendDetailsMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated string player_id = 1;</code>
     */
    private $player_id;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Social\GetFriendDetailsMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated string player_id = 1;</code>
     */
    public function getPlayerId()
    {
        return $this->player_id;
    }

    /**
     * <code>repeated string player_id = 1;</code>
     */
    public function setPlayerId(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->player_id = $var;
    }

}

