<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Badge/GymBadgeStats.proto

namespace GPBMetadata\POGOProtos\Data\Badge;

class GymBadgeStats
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Gym\GymBattle::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7020a29504f474f50726f746f732f446174612f42616467652f47796d" .
            "426164676553746174732e70726f746f1215504f474f50726f746f732e44" .
            "6174612e42616467651a23504f474f50726f746f732f446174612f47796d" .
            "2f47796d426174746c652e70726f746f22c5010a0d47796d426164676553" .
            "74617473121e0a16746f74616c5f74696d655f646566656e6465645f6d73" .
            "18012001280412170a0f6e756d5f626174746c65735f776f6e1802200128" .
            "0d12180a106e756d5f626174746c65735f6c6f737418052001280d12170a" .
            "0f6e756d5f626572726965735f66656418032001280d12130a0b6e756d5f" .
            "6465706c6f797318042001280d12330a0b67796d5f626174746c6573180f" .
            "2003280b321e2e504f474f50726f746f732e446174612e47796d2e47796d" .
            "426174746c65620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

