<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Telemetry/DeployPokemonTelemetry.proto

namespace POGOProtos\Data\Telemetry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Telemetry.DeployPokemonTelemetry</code>
 */
class DeployPokemonTelemetry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Telemetry.PokemonTelemetry pokemon = 2;</code>
     */
    private $pokemon = null;
    /**
     * Generated from protobuf field <code>string gym_id = 3;</code>
     */
    private $gym_id = '';
    /**
     * Generated from protobuf field <code>int32 team = 4;</code>
     */
    private $team = 0;
    /**
     * Generated from protobuf field <code>int32 defender_count = 5;</code>
     */
    private $defender_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type \POGOProtos\Data\Telemetry\PokemonTelemetry $pokemon
     *     @type string $gym_id
     *     @type int $team
     *     @type int $defender_count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Telemetry\DeployPokemonTelemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>int32 status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkInt32($var);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Telemetry.PokemonTelemetry pokemon = 2;</code>
     * @return \POGOProtos\Data\Telemetry\PokemonTelemetry
     */
    public function getPokemon()
    {
        return $this->pokemon;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Telemetry.PokemonTelemetry pokemon = 2;</code>
     * @param \POGOProtos\Data\Telemetry\PokemonTelemetry $var
     * @return $this
     */
    public function setPokemon($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Telemetry\PokemonTelemetry::class);
        $this->pokemon = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gym_id = 3;</code>
     * @return string
     */
    public function getGymId()
    {
        return $this->gym_id;
    }

    /**
     * Generated from protobuf field <code>string gym_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGymId($var)
    {
        GPBUtil::checkString($var, True);
        $this->gym_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 team = 4;</code>
     * @return int
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * Generated from protobuf field <code>int32 team = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setTeam($var)
    {
        GPBUtil::checkInt32($var);
        $this->team = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 defender_count = 5;</code>
     * @return int
     */
    public function getDefenderCount()
    {
        return $this->defender_count;
    }

    /**
     * Generated from protobuf field <code>int32 defender_count = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDefenderCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->defender_count = $var;

        return $this;
    }

}

