<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Telemetry/PokemonInventoryTelemetry.proto

namespace POGOProtos\Data\Telemetry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Telemetry.PokemonInventoryTelemetry</code>
 */
class PokemonInventoryTelemetry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.PokemonInventoryTelemetryIds pokemon_inventory_click_ids = 1;</code>
     */
    private $pokemon_inventory_click_ids = 0;
    /**
     * Generated from protobuf field <code>string sort_id = 2;</code>
     */
    private $sort_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $pokemon_inventory_click_ids
     *     @type string $sort_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Telemetry\PokemonInventoryTelemetry::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.PokemonInventoryTelemetryIds pokemon_inventory_click_ids = 1;</code>
     * @return int
     */
    public function getPokemonInventoryClickIds()
    {
        return $this->pokemon_inventory_click_ids;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.PokemonInventoryTelemetryIds pokemon_inventory_click_ids = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPokemonInventoryClickIds($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\PokemonInventoryTelemetryIds::class);
        $this->pokemon_inventory_click_ids = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sort_id = 2;</code>
     * @return string
     */
    public function getSortId()
    {
        return $this->sort_id;
    }

    /**
     * Generated from protobuf field <code>string sort_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSortId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sort_id = $var;

        return $this;
    }

}

