<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/EventSettings.proto

namespace POGOProtos\Settings;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Settings.EventSettings</code>
 */
class EventSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string condolence_ribbon_country = 1;</code>
     */
    private $condolence_ribbon_country;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $condolence_ribbon_country
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Settings\EventSettings::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string condolence_ribbon_country = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCondolenceRibbonCountry()
    {
        return $this->condolence_ribbon_country;
    }

    /**
     * Generated from protobuf field <code>repeated string condolence_ribbon_country = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCondolenceRibbonCountry($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->condolence_ribbon_country = $arr;

        return $this;
    }

}

