<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/PokemonGlobalSettings.proto

namespace POGOProtos\Settings;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Settings.PokemonGlobalSettings</code>
 */
class PokemonGlobalSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool enable_camo_shader = 1;</code>
     */
    private $enable_camo_shader = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enable_camo_shader
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Settings\PokemonGlobalSettings::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool enable_camo_shader = 1;</code>
     * @return bool
     */
    public function getEnableCamoShader()
    {
        return $this->enable_camo_shader;
    }

    /**
     * Generated from protobuf field <code>bool enable_camo_shader = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableCamoShader($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_camo_shader = $var;

        return $this;
    }

}

