<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/PokemonDisplay.proto

namespace GPBMetadata\POGOProtos\Data;

class PokemonDisplay
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\Costume::initOnce();
        \GPBMetadata\POGOProtos\Enums\Form::initOnce();
        \GPBMetadata\POGOProtos\Enums\Gender::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9020a24504f474f50726f746f732f446174612f506f6b656d6f6e4469" .
            "73706c61792e70726f746f120f504f474f50726f746f732e446174611a1e" .
            "504f474f50726f746f732f456e756d732f436f7374756d652e70726f746f" .
            "1a1b504f474f50726f746f732f456e756d732f466f726d2e70726f746f1a" .
            "1d504f474f50726f746f732f456e756d732f47656e6465722e70726f746f" .
            "229b010a0e506f6b656d6f6e446973706c6179122a0a07636f7374756d65" .
            "18012001280e32192e504f474f50726f746f732e456e756d732e436f7374" .
            "756d6512280a0667656e64657218022001280e32182e504f474f50726f74" .
            "6f732e456e756d732e47656e646572120d0a057368696e79180320012808" .
            "12240a04666f726d18042001280e32162e504f474f50726f746f732e456e" .
            "756d732e466f726d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

