<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Trading/Trading.proto

namespace POGOProtos\Data\Trading;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Trading.Trading</code>
 */
class Trading extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Trading.Trading.TradingState state = 1;</code>
     */
    private $state = 0;
    /**
     * Generated from protobuf field <code>uint64 expiration_ms = 2;</code>
     */
    private $expiration_ms = 0;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Trading.TradingPlayer player = 3;</code>
     */
    private $player = null;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Trading.TradingPlayer friend = 4;</code>
     */
    private $friend = null;
    /**
     * Generated from protobuf field <code>int64 trading_s2_cell_id = 5;</code>
     */
    private $trading_s2_cell_id = 0;
    /**
     * Generated from protobuf field <code>string transaction_log = 6;</code>
     */
    private $transaction_log = '';
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Friends.FriendshipLevelData friendship_level_data = 7;</code>
     */
    private $friendship_level_data = null;
    /**
     * Generated from protobuf field <code>bool is_special_trading = 8;</code>
     */
    private $is_special_trading = false;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Friends.FriendshipLevelData pre_trading_friendship_level = 9;</code>
     */
    private $pre_trading_friendship_level = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $state
     *     @type int|string $expiration_ms
     *     @type \POGOProtos\Data\Trading\TradingPlayer $player
     *     @type \POGOProtos\Data\Trading\TradingPlayer $friend
     *     @type int|string $trading_s2_cell_id
     *     @type string $transaction_log
     *     @type \POGOProtos\Data\Friends\FriendshipLevelData $friendship_level_data
     *     @type bool $is_special_trading
     *     @type \POGOProtos\Data\Friends\FriendshipLevelData $pre_trading_friendship_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Trading\Trading::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Trading.Trading.TradingState state = 1;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Trading.Trading.TradingState state = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Data\Trading\Trading_TradingState::class);
        $this->state = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expiration_ms = 2;</code>
     * @return int|string
     */
    public function getExpirationMs()
    {
        return $this->expiration_ms;
    }

    /**
     * Generated from protobuf field <code>uint64 expiration_ms = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpirationMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->expiration_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Trading.TradingPlayer player = 3;</code>
     * @return \POGOProtos\Data\Trading\TradingPlayer
     */
    public function getPlayer()
    {
        return $this->player;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Trading.TradingPlayer player = 3;</code>
     * @param \POGOProtos\Data\Trading\TradingPlayer $var
     * @return $this
     */
    public function setPlayer($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Trading\TradingPlayer::class);
        $this->player = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Trading.TradingPlayer friend = 4;</code>
     * @return \POGOProtos\Data\Trading\TradingPlayer
     */
    public function getFriend()
    {
        return $this->friend;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Trading.TradingPlayer friend = 4;</code>
     * @param \POGOProtos\Data\Trading\TradingPlayer $var
     * @return $this
     */
    public function setFriend($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Trading\TradingPlayer::class);
        $this->friend = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 trading_s2_cell_id = 5;</code>
     * @return int|string
     */
    public function getTradingS2CellId()
    {
        return $this->trading_s2_cell_id;
    }

    /**
     * Generated from protobuf field <code>int64 trading_s2_cell_id = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTradingS2CellId($var)
    {
        GPBUtil::checkInt64($var);
        $this->trading_s2_cell_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string transaction_log = 6;</code>
     * @return string
     */
    public function getTransactionLog()
    {
        return $this->transaction_log;
    }

    /**
     * Generated from protobuf field <code>string transaction_log = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionLog($var)
    {
        GPBUtil::checkString($var, True);
        $this->transaction_log = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Friends.FriendshipLevelData friendship_level_data = 7;</code>
     * @return \POGOProtos\Data\Friends\FriendshipLevelData
     */
    public function getFriendshipLevelData()
    {
        return $this->friendship_level_data;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Friends.FriendshipLevelData friendship_level_data = 7;</code>
     * @param \POGOProtos\Data\Friends\FriendshipLevelData $var
     * @return $this
     */
    public function setFriendshipLevelData($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Friends\FriendshipLevelData::class);
        $this->friendship_level_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_special_trading = 8;</code>
     * @return bool
     */
    public function getIsSpecialTrading()
    {
        return $this->is_special_trading;
    }

    /**
     * Generated from protobuf field <code>bool is_special_trading = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsSpecialTrading($var)
    {
        GPBUtil::checkBool($var);
        $this->is_special_trading = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Friends.FriendshipLevelData pre_trading_friendship_level = 9;</code>
     * @return \POGOProtos\Data\Friends\FriendshipLevelData
     */
    public function getPreTradingFriendshipLevel()
    {
        return $this->pre_trading_friendship_level;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Friends.FriendshipLevelData pre_trading_friendship_level = 9;</code>
     * @param \POGOProtos\Data\Friends\FriendshipLevelData $var
     * @return $this
     */
    public function setPreTradingFriendshipLevel($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Friends\FriendshipLevelData::class);
        $this->pre_trading_friendship_level = $var;

        return $this;
    }

}

