<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/BattleAttributes.proto

namespace POGOProtos\Settings\Master\Item;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Settings.Master.Item.BattleAttributes</code>
 */
class BattleAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float sta_percent = 1;</code>
     */
    private $sta_percent = 0.0;
    /**
     * Generated from protobuf field <code>float atk_percent = 2;</code>
     */
    private $atk_percent = 0.0;
    /**
     * Generated from protobuf field <code>float def_percent = 3;</code>
     */
    private $def_percent = 0.0;
    /**
     * Generated from protobuf field <code>float duration_s = 4;</code>
     */
    private $duration_s = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $sta_percent
     *     @type float $atk_percent
     *     @type float $def_percent
     *     @type float $duration_s
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Settings\Master\Item\BattleAttributes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float sta_percent = 1;</code>
     * @return float
     */
    public function getStaPercent()
    {
        return $this->sta_percent;
    }

    /**
     * Generated from protobuf field <code>float sta_percent = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setStaPercent($var)
    {
        GPBUtil::checkFloat($var);
        $this->sta_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float atk_percent = 2;</code>
     * @return float
     */
    public function getAtkPercent()
    {
        return $this->atk_percent;
    }

    /**
     * Generated from protobuf field <code>float atk_percent = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setAtkPercent($var)
    {
        GPBUtil::checkFloat($var);
        $this->atk_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float def_percent = 3;</code>
     * @return float
     */
    public function getDefPercent()
    {
        return $this->def_percent;
    }

    /**
     * Generated from protobuf field <code>float def_percent = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setDefPercent($var)
    {
        GPBUtil::checkFloat($var);
        $this->def_percent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float duration_s = 4;</code>
     * @return float
     */
    public function getDurationS()
    {
        return $this->duration_s;
    }

    /**
     * Generated from protobuf field <code>float duration_s = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setDurationS($var)
    {
        GPBUtil::checkFloat($var);
        $this->duration_s = $var;

        return $this;
    }

}

