<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/EggIncubatorAttributes.proto

namespace POGOProtos\Settings\Master\Item;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Settings.Master.Item.EggIncubatorAttributes</code>
 */
class EggIncubatorAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Inventory.EggIncubatorType incubator_type = 1;</code>
     */
    private $incubator_type = 0;
    /**
     * Generated from protobuf field <code>int32 uses = 2;</code>
     */
    private $uses = 0;
    /**
     * Generated from protobuf field <code>float distance_multiplier = 3;</code>
     */
    private $distance_multiplier = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $incubator_type
     *     @type int $uses
     *     @type float $distance_multiplier
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Settings\Master\Item\EggIncubatorAttributes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Inventory.EggIncubatorType incubator_type = 1;</code>
     * @return int
     */
    public function getIncubatorType()
    {
        return $this->incubator_type;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Inventory.EggIncubatorType incubator_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setIncubatorType($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Inventory\EggIncubatorType::class);
        $this->incubator_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 uses = 2;</code>
     * @return int
     */
    public function getUses()
    {
        return $this->uses;
    }

    /**
     * Generated from protobuf field <code>int32 uses = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUses($var)
    {
        GPBUtil::checkInt32($var);
        $this->uses = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float distance_multiplier = 3;</code>
     * @return float
     */
    public function getDistanceMultiplier()
    {
        return $this->distance_multiplier;
    }

    /**
     * Generated from protobuf field <code>float distance_multiplier = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setDistanceMultiplier($var)
    {
        GPBUtil::checkFloat($var);
        $this->distance_multiplier = $var;

        return $this;
    }

}

