<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/IncenseAttributes.proto

namespace POGOProtos\Settings\Master\Item;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Settings\Master\Item\IncenseAttributes\SpawnTablePokemon instead.
     * @deprecated
     */
    class IncenseAttributes_SpawnTablePokemon {}
}
class_exists(IncenseAttributes\SpawnTablePokemon::class);
@trigger_error('POGOProtos\Settings\Master\Item\IncenseAttributes_SpawnTablePokemon is deprecated and will be removed in the next major release. Use POGOProtos\Settings\Master\Item\IncenseAttributes\SpawnTablePokemon instead', E_USER_DEPRECATED);

