<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/CameraSettings.proto

namespace POGOProtos\Settings\Master;

/**
 * Protobuf enum <code>POGOProtos.Settings.Master.CameraSettings.CameraInterpolation</code>
 */
class CameraSettings_CameraInterpolation
{
    /**
     * <code>CAM_INTERP_CUT = 0;</code>
     */
    const CAM_INTERP_CUT = 0;
    /**
     * <code>CAM_INTERP_LINEAR = 1;</code>
     */
    const CAM_INTERP_LINEAR = 1;
    /**
     * <code>CAM_INTERP_SMOOTH = 2;</code>
     */
    const CAM_INTERP_SMOOTH = 2;
    /**
     * <code>CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE = 3;</code>
     */
    const CAM_INTERP_SMOOTH_ROT_LINEAR_MOVE = 3;
    /**
     * <code>CAM_INTERP_DEPENDS = 4;</code>
     */
    const CAM_INTERP_DEPENDS = 4;
}

