<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/CombatLeagueSettings.proto

namespace POGOProtos\Settings\Master;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Settings.Master.CombatLeagueSettings</code>
 */
class CombatLeagueSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string combat_league_template_id = 1;</code>
     */
    private $combat_league_template_id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $combat_league_template_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Settings\Master\CombatLeagueSettings::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string combat_league_template_id = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCombatLeagueTemplateId()
    {
        return $this->combat_league_template_id;
    }

    /**
     * Generated from protobuf field <code>repeated string combat_league_template_id = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCombatLeagueTemplateId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->combat_league_template_id = $arr;

        return $this;
    }

}

