<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/CombatLeague.proto

namespace POGOProtos\Settings\Master;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Settings.Master.CombatLeague</code>
 */
class CombatLeague extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string title = 1;</code>
     */
    private $title = '';
    /**
     * Generated from protobuf field <code>bool enabled = 2;</code>
     */
    private $enabled = false;
    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Combat.UnlockCondition unlock_condition = 3;</code>
     */
    private $unlock_condition;
    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Combat.PokemonCondition pokemon_condition = 4;</code>
     */
    private $pokemon_condition;
    /**
     * Generated from protobuf field <code>string icon_url = 5;</code>
     */
    private $icon_url = '';
    /**
     * Generated from protobuf field <code>int32 pokemon_count = 6;</code>
     */
    private $pokemon_count = 0;
    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Enums.PokemonId banned_pokemon = 7;</code>
     */
    private $banned_pokemon;
    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.BadgeType badge_type = 8;</code>
     */
    private $badge_type = 0;
    /**
     * Generated from protobuf field <code>int32 minigame_defense_chance_limit = 9;</code>
     */
    private $minigame_defense_chance_limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $title
     *     @type bool $enabled
     *     @type \POGOProtos\Data\Combat\UnlockCondition[]|\Google\Protobuf\Internal\RepeatedField $unlock_condition
     *     @type \POGOProtos\Data\Combat\PokemonCondition[]|\Google\Protobuf\Internal\RepeatedField $pokemon_condition
     *     @type string $icon_url
     *     @type int $pokemon_count
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $banned_pokemon
     *     @type int $badge_type
     *     @type int $minigame_defense_chance_limit
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Settings\Master\CombatLeague::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Generated from protobuf field <code>string title = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enabled = 2;</code>
     * @return bool
     */
    public function getEnabled()
    {
        return $this->enabled;
    }

    /**
     * Generated from protobuf field <code>bool enabled = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Combat.UnlockCondition unlock_condition = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUnlockCondition()
    {
        return $this->unlock_condition;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Combat.UnlockCondition unlock_condition = 3;</code>
     * @param \POGOProtos\Data\Combat\UnlockCondition[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUnlockCondition($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\Combat\UnlockCondition::class);
        $this->unlock_condition = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Combat.PokemonCondition pokemon_condition = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPokemonCondition()
    {
        return $this->pokemon_condition;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Combat.PokemonCondition pokemon_condition = 4;</code>
     * @param \POGOProtos\Data\Combat\PokemonCondition[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPokemonCondition($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\Combat\PokemonCondition::class);
        $this->pokemon_condition = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string icon_url = 5;</code>
     * @return string
     */
    public function getIconUrl()
    {
        return $this->icon_url;
    }

    /**
     * Generated from protobuf field <code>string icon_url = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setIconUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->icon_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pokemon_count = 6;</code>
     * @return int
     */
    public function getPokemonCount()
    {
        return $this->pokemon_count;
    }

    /**
     * Generated from protobuf field <code>int32 pokemon_count = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPokemonCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->pokemon_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Enums.PokemonId banned_pokemon = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBannedPokemon()
    {
        return $this->banned_pokemon;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Enums.PokemonId banned_pokemon = 7;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBannedPokemon($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \POGOProtos\Enums\PokemonId::class);
        $this->banned_pokemon = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.BadgeType badge_type = 8;</code>
     * @return int
     */
    public function getBadgeType()
    {
        return $this->badge_type;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.BadgeType badge_type = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setBadgeType($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\BadgeType::class);
        $this->badge_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 minigame_defense_chance_limit = 9;</code>
     * @return int
     */
    public function getMinigameDefenseChanceLimit()
    {
        return $this->minigame_defense_chance_limit;
    }

    /**
     * Generated from protobuf field <code>int32 minigame_defense_chance_limit = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setMinigameDefenseChanceLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->minigame_defense_chance_limit = $var;

        return $this;
    }

}

