<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/IapItemCategoryDisplay.proto

namespace POGOProtos\Settings\Master;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Settings.Master.IapItemCategoryDisplay</code>
 */
class IapItemCategoryDisplay extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Enums.HoloIapItemCategory category = 1;</code>
     */
    private $category = 0;
    /**
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <code>bool hidden = 3;</code>
     */
    private $hidden = false;
    /**
     * <code>int32 sort_order = 4;</code>
     */
    private $sort_order = 0;
    /**
     * <code>bool banner_enabled = 5;</code>
     */
    private $banner_enabled = false;
    /**
     * <code>string banner_title = 6;</code>
     */
    private $banner_title = '';
    /**
     * <code>string image_url = 7;</code>
     */
    private $image_url = '';
    /**
     * <code>string description = 8;</code>
     */
    private $description = '';

    public function __construct() {
        \GPBMetadata\POGOProtos\Settings\Master\IapItemCategoryDisplay::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Enums.HoloIapItemCategory category = 1;</code>
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * <code>.POGOProtos.Enums.HoloIapItemCategory category = 1;</code>
     */
    public function setCategory($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\HoloIapItemCategory::class);
        $this->category = $var;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>bool hidden = 3;</code>
     */
    public function getHidden()
    {
        return $this->hidden;
    }

    /**
     * <code>bool hidden = 3;</code>
     */
    public function setHidden($var)
    {
        GPBUtil::checkBool($var);
        $this->hidden = $var;
    }

    /**
     * <code>int32 sort_order = 4;</code>
     */
    public function getSortOrder()
    {
        return $this->sort_order;
    }

    /**
     * <code>int32 sort_order = 4;</code>
     */
    public function setSortOrder($var)
    {
        GPBUtil::checkInt32($var);
        $this->sort_order = $var;
    }

    /**
     * <code>bool banner_enabled = 5;</code>
     */
    public function getBannerEnabled()
    {
        return $this->banner_enabled;
    }

    /**
     * <code>bool banner_enabled = 5;</code>
     */
    public function setBannerEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->banner_enabled = $var;
    }

    /**
     * <code>string banner_title = 6;</code>
     */
    public function getBannerTitle()
    {
        return $this->banner_title;
    }

    /**
     * <code>string banner_title = 6;</code>
     */
    public function setBannerTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->banner_title = $var;
    }

    /**
     * <code>string image_url = 7;</code>
     */
    public function getImageUrl()
    {
        return $this->image_url;
    }

    /**
     * <code>string image_url = 7;</code>
     */
    public function setImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->image_url = $var;
    }

    /**
     * <code>string description = 8;</code>
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * <code>string description = 8;</code>
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

}

