<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Item/IncenseAttributes.proto

namespace GPBMetadata\POGOProtos\Settings\Master\Item;

class IncenseAttributes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\PokemonType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7030a37504f474f50726f746f732f53657474696e67732f4d61737465" .
            "722f4974656d2f496e63656e7365417474726962757465732e70726f746f" .
            "121f504f474f50726f746f732e53657474696e67732e4d61737465722e49" .
            "74656d22d2020a11496e63656e73654174747269627574657312200a1869" .
            "6e63656e73655f6c69666574696d655f7365636f6e647318012001280512" .
            "330a0c706f6b656d6f6e5f7479706518022003280e321d2e504f474f5072" .
            "6f746f732e456e756d732e506f6b656d6f6e5479706512280a20706f6b65" .
            "6d6f6e5f696e63656e73655f747970655f70726f626162696c6974791803" .
            "2001280212300a287374616e64696e675f74696d655f6265747765656e5f" .
            "656e636f756e746572735f7365636f6e6473180420012805122d0a256d6f" .
            "76696e675f74696d655f6265747765656e5f656e636f756e7465725f7365" .
            "636f6e647318052001280512350a2d64697374616e63655f726571756972" .
            "65645f666f725f73686f727465725f696e74657276616c5f6d6574657273" .
            "18062001280512240a1c706f6b656d6f6e5f6174747261637465645f6c65" .
            "6e6774685f736563180720012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

