<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Battle/BattleState.proto

namespace POGOProtos\Data\Battle;

/**
 * Protobuf type <code>POGOProtos.Data.Battle.BattleState</code>
 */
class BattleState
{
    /**
     * Generated from protobuf enum <code>STATE_UNSET = 0;</code>
     */
    const STATE_UNSET = 0;
    /**
     * Generated from protobuf enum <code>ACTIVE = 1;</code>
     */
    const ACTIVE = 1;
    /**
     * Generated from protobuf enum <code>VICTORY = 2;</code>
     */
    const VICTORY = 2;
    /**
     * Generated from protobuf enum <code>DEFEATED = 3;</code>
     */
    const DEFEATED = 3;
    /**
     * Generated from protobuf enum <code>TIMED_OUT = 4;</code>
     */
    const TIMED_OUT = 4;
}

