<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Battle/Battle.proto

namespace POGOProtos\Data\Battle;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Battle.Battle</code>
 */
class Battle extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 battle_start_ms = 1;</code>
     */
    private $battle_start_ms = 0;
    /**
     * Generated from protobuf field <code>int64 battle_end_ms = 2;</code>
     */
    private $battle_end_ms = 0;
    /**
     * Generated from protobuf field <code>string battle_id = 3;</code>
     */
    private $battle_id = '';
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Battle.BattleParticipant defender = 4;</code>
     */
    private $defender = null;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Battle.BattleLog battle_log = 5;</code>
     */
    private $battle_log = null;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Battle.BattleParticipant attacker = 6;</code>
     */
    private $attacker = null;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.PokemonDisplay.WeatherCondition weather_condition = 7;</code>
     */
    private $weather_condition = 0;
    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.FriendshipLevelMilestone highest_friendship_milestone = 8;</code>
     */
    private $highest_friendship_milestone = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $battle_start_ms
     *     @type int|string $battle_end_ms
     *     @type string $battle_id
     *     @type \POGOProtos\Data\Battle\BattleParticipant $defender
     *     @type \POGOProtos\Data\Battle\BattleLog $battle_log
     *     @type \POGOProtos\Data\Battle\BattleParticipant $attacker
     *     @type int $weather_condition
     *     @type int $highest_friendship_milestone
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Battle\Battle::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 battle_start_ms = 1;</code>
     * @return int|string
     */
    public function getBattleStartMs()
    {
        return $this->battle_start_ms;
    }

    /**
     * Generated from protobuf field <code>int64 battle_start_ms = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBattleStartMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->battle_start_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 battle_end_ms = 2;</code>
     * @return int|string
     */
    public function getBattleEndMs()
    {
        return $this->battle_end_ms;
    }

    /**
     * Generated from protobuf field <code>int64 battle_end_ms = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBattleEndMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->battle_end_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string battle_id = 3;</code>
     * @return string
     */
    public function getBattleId()
    {
        return $this->battle_id;
    }

    /**
     * Generated from protobuf field <code>string battle_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBattleId($var)
    {
        GPBUtil::checkString($var, True);
        $this->battle_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Battle.BattleParticipant defender = 4;</code>
     * @return \POGOProtos\Data\Battle\BattleParticipant
     */
    public function getDefender()
    {
        return $this->defender;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Battle.BattleParticipant defender = 4;</code>
     * @param \POGOProtos\Data\Battle\BattleParticipant $var
     * @return $this
     */
    public function setDefender($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Battle\BattleParticipant::class);
        $this->defender = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Battle.BattleLog battle_log = 5;</code>
     * @return \POGOProtos\Data\Battle\BattleLog
     */
    public function getBattleLog()
    {
        return $this->battle_log;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Battle.BattleLog battle_log = 5;</code>
     * @param \POGOProtos\Data\Battle\BattleLog $var
     * @return $this
     */
    public function setBattleLog($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Battle\BattleLog::class);
        $this->battle_log = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Battle.BattleParticipant attacker = 6;</code>
     * @return \POGOProtos\Data\Battle\BattleParticipant
     */
    public function getAttacker()
    {
        return $this->attacker;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Battle.BattleParticipant attacker = 6;</code>
     * @param \POGOProtos\Data\Battle\BattleParticipant $var
     * @return $this
     */
    public function setAttacker($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Battle\BattleParticipant::class);
        $this->attacker = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.PokemonDisplay.WeatherCondition weather_condition = 7;</code>
     * @return int
     */
    public function getWeatherCondition()
    {
        return $this->weather_condition;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.PokemonDisplay.WeatherCondition weather_condition = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setWeatherCondition($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Data\PokemonDisplay_WeatherCondition::class);
        $this->weather_condition = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.FriendshipLevelMilestone highest_friendship_milestone = 8;</code>
     * @return int
     */
    public function getHighestFriendshipMilestone()
    {
        return $this->highest_friendship_milestone;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.FriendshipLevelMilestone highest_friendship_milestone = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setHighestFriendshipMilestone($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\FriendshipLevelMilestone::class);
        $this->highest_friendship_milestone = $var;

        return $this;
    }

}

