<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Battle/BattlePokemonInfo.proto

namespace POGOProtos\Data\Battle;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Battle.BattlePokemonInfo</code>
 */
class BattlePokemonInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.PokemonData pokemon_data = 1;</code>
     */
    private $pokemon_data = null;
    /**
     * Generated from protobuf field <code>int32 current_health = 2;</code>
     */
    private $current_health = 0;
    /**
     * Generated from protobuf field <code>int32 current_energy = 3;</code>
     */
    private $current_energy = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \POGOProtos\Data\PokemonData $pokemon_data
     *     @type int $current_health
     *     @type int $current_energy
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Battle\BattlePokemonInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.PokemonData pokemon_data = 1;</code>
     * @return \POGOProtos\Data\PokemonData
     */
    public function getPokemonData()
    {
        return $this->pokemon_data;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.PokemonData pokemon_data = 1;</code>
     * @param \POGOProtos\Data\PokemonData $var
     * @return $this
     */
    public function setPokemonData($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\PokemonData::class);
        $this->pokemon_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 current_health = 2;</code>
     * @return int
     */
    public function getCurrentHealth()
    {
        return $this->current_health;
    }

    /**
     * Generated from protobuf field <code>int32 current_health = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentHealth($var)
    {
        GPBUtil::checkInt32($var);
        $this->current_health = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 current_energy = 3;</code>
     * @return int
     */
    public function getCurrentEnergy()
    {
        return $this->current_energy;
    }

    /**
     * Generated from protobuf field <code>int32 current_energy = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrentEnergy($var)
    {
        GPBUtil::checkInt32($var);
        $this->current_energy = $var;

        return $this;
    }

}

