<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SetPlayerTeamResponse.proto

namespace POGOProtos\Networking\Responses\SetPlayerTeamResponse;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.SetPlayerTeamResponse.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>UNSET = 0;</code>
     */
    const PBUNSET = 0;
    /**
     * Generated from protobuf enum <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
    /**
     * Generated from protobuf enum <code>TEAM_ALREADY_SET = 2;</code>
     */
    const TEAM_ALREADY_SET = 2;
    /**
     * Generated from protobuf enum <code>FAILURE = 3;</code>
     */
    const FAILURE = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \POGOProtos\Networking\Responses\SetPlayerTeamResponse_Status::class);

