<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/EvolutionV2Settings.proto

namespace GPBMetadata\POGOProtos\Settings;

class EvolutionV2Settings
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a770a2d504f474f50726f746f732f53657474696e67732f45766f6c7574" .
            "696f6e563253657474696e67732e70726f746f1213504f474f50726f746f" .
            "732e53657474696e677322290a1345766f6c7574696f6e56325365747469" .
            "6e677312120a0a69735f656e61626c6564180120012808620670726f746f" .
            "33"
        ));

        static::$is_initialized = true;
    }
}

