<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/PokemonGlobalSettings.proto

namespace GPBMetadata\POGOProtos\Settings;

class PokemonGlobalSettings
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a83010a2f504f474f50726f746f732f53657474696e67732f506f6b656d" .
            "6f6e476c6f62616c53657474696e67732e70726f746f1213504f474f5072" .
            "6f746f732e53657474696e677322330a15506f6b656d6f6e476c6f62616c" .
            "53657474696e6773121a0a12656e61626c655f63616d6f5f736861646572" .
            "180120012808620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

