<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Inbox/ClientInbox.proto

namespace POGOProtos\Data\Inbox\ClientInbox;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Inbox.ClientInbox.TemplateVariable</code>
 */
class TemplateVariable extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>string literal = 2;</code>
     */
    private $literal = '';
    /**
     * Generated from protobuf field <code>string key = 3;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>string lookup_table = 4;</code>
     */
    private $lookup_table = '';
    /**
     * Generated from protobuf field <code>bytes byte_value = 5;</code>
     */
    private $byte_value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $literal
     *     @type string $key
     *     @type string $lookup_table
     *     @type string $byte_value
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Inbox\ClientInbox::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string literal = 2;</code>
     * @return string
     */
    public function getLiteral()
    {
        return $this->literal;
    }

    /**
     * Generated from protobuf field <code>string literal = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLiteral($var)
    {
        GPBUtil::checkString($var, True);
        $this->literal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string lookup_table = 4;</code>
     * @return string
     */
    public function getLookupTable()
    {
        return $this->lookup_table;
    }

    /**
     * Generated from protobuf field <code>string lookup_table = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLookupTable($var)
    {
        GPBUtil::checkString($var, True);
        $this->lookup_table = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes byte_value = 5;</code>
     * @return string
     */
    public function getByteValue()
    {
        return $this->byte_value;
    }

    /**
     * Generated from protobuf field <code>bytes byte_value = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setByteValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->byte_value = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TemplateVariable::class, \POGOProtos\Data\Inbox\ClientInbox_TemplateVariable::class);

