<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Envelopes/ResponseEnvelope.proto

namespace POGOProtos\Networking\Envelopes;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Envelopes\ResponseEnvelope\StatusCode instead.
     * @deprecated
     */
    class ResponseEnvelope_StatusCode {}
}
class_exists(ResponseEnvelope\StatusCode::class);
@trigger_error('POGOProtos\Networking\Envelopes\ResponseEnvelope_StatusCode is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Envelopes\ResponseEnvelope\StatusCode instead', E_USER_DEPRECATED);

