<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/InternalAuth.proto

namespace GPBMetadata\POGOProtos\Networking\Platform;

class InternalAuth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaa010a31504f474f50726f746f732f4e6574776f726b696e672f506c61" .
            "74666f726d2f496e7465726e616c417574682e70726f746f121e504f474f" .
            "50726f746f732e4e6574776f726b696e672e506c6174666f726d224d0a0c" .
            "496e7465726e616c41757468120d0a05656d61696c18012001280912110a" .
            "09706c617965725f6964180220012809120e0a066170705f696418032001" .
            "2809120b0a036b6579180420012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

