<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/PlayerCamera.proto

namespace POGOProtos\Data\Player;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Player.PlayerCamera</code>
 */
class PlayerCamera extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_default_camera = 1;</code>
     */
    private $is_default_camera = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_default_camera
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Player\PlayerCamera::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_default_camera = 1;</code>
     * @return bool
     */
    public function getIsDefaultCamera()
    {
        return $this->is_default_camera;
    }

    /**
     * Generated from protobuf field <code>bool is_default_camera = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDefaultCamera($var)
    {
        GPBUtil::checkBool($var);
        $this->is_default_camera = $var;

        return $this;
    }

}

