<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/PlayerReputation.proto

namespace POGOProtos\Data\Player;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Data.Player.PlayerReputation</code>
 */
class PlayerReputation extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 account_age_ms = 1;</code>
     */
    private $account_age_ms = 0;
    /**
     * <code>int64 player_level = 2;</code>
     */
    private $player_level = 0;
    /**
     * <code>repeated .POGOProtos.Data.Player.PlayerReputation.CheatReputation cheat_reputation = 3;</code>
     */
    private $cheat_reputation;

    public function __construct() {
        \GPBMetadata\POGOProtos\Data\Player\PlayerReputation::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 account_age_ms = 1;</code>
     */
    public function getAccountAgeMs()
    {
        return $this->account_age_ms;
    }

    /**
     * <code>int64 account_age_ms = 1;</code>
     */
    public function setAccountAgeMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->account_age_ms = $var;
    }

    /**
     * <code>int64 player_level = 2;</code>
     */
    public function getPlayerLevel()
    {
        return $this->player_level;
    }

    /**
     * <code>int64 player_level = 2;</code>
     */
    public function setPlayerLevel($var)
    {
        GPBUtil::checkInt64($var);
        $this->player_level = $var;
    }

    /**
     * <code>repeated .POGOProtos.Data.Player.PlayerReputation.CheatReputation cheat_reputation = 3;</code>
     */
    public function getCheatReputation()
    {
        return $this->cheat_reputation;
    }

    /**
     * <code>repeated .POGOProtos.Data.Player.PlayerReputation.CheatReputation cheat_reputation = 3;</code>
     */
    public function setCheatReputation(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, POGOProtos\Data\Player\PlayerReputation_CheatReputation::class);
        $this->cheat_reputation = $var;
    }

}

