<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/UserAttributes.proto

namespace GPBMetadata\POGOProtos\Data\Player;

class UserAttributes
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87020a2b504f474f50726f746f732f446174612f506c617965722f5573" .
            "6572417474726962757465732e70726f746f1216504f474f50726f746f73" .
            "2e446174612e506c6179657222b7010a0e55736572417474726962757465" .
            "73120d0a056c6576656c180120012805120a0a027870180220012803120e" .
            "0a0661766174617218032001280512120a0a6974656d5f636f756e741804" .
            "2001280312150a0d706f6b656d6f6e5f636f756e7418052001280312160a" .
            "0e706f6b65636f696e5f636f756e74180620012803120c0a047465616d18" .
            "072001280512140a0c63617463685f73747265616b18082001280512130a" .
            "0b7370696e5f73747265616b180920012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

