<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Player/UserIssueWeatherReport.proto

namespace GPBMetadata\POGOProtos\Data\Player;

class UserIssueWeatherReport
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8010a33504f474f50726f746f732f446174612f506c617965722f5573" .
            "65724973737565576561746865725265706f72742e70726f746f1216504f" .
            "474f50726f746f732e446174612e506c6179657222710a16557365724973" .
            "737565576561746865725265706f7274121a0a1267616d65706c61796572" .
            "5f7765617468657218012001280912140a0c616c6572745f616374697665" .
            "18022001280812100a08736576657269747918032001280512130a0b7573" .
            "65725f7265706f7274180420012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

