<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/PlatformClientActionsResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.AddLoginActionResponse</code>
 */
class AddLoginActionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool success = 1;</code>
     */
    private $success = false;
    /**
     * <code>repeated .POGOProtos.Data.Login.LoginDetail login_detail = 2;</code>
     */
    private $login_detail;
    /**
     * <code>.POGOProtos.Networking.Responses.AddLoginActionResponse.Status status = 3;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\PlatformClientActionsResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;
    }

    /**
     * <code>repeated .POGOProtos.Data.Login.LoginDetail login_detail = 2;</code>
     */
    public function getLoginDetail()
    {
        return $this->login_detail;
    }

    /**
     * <code>repeated .POGOProtos.Data.Login.LoginDetail login_detail = 2;</code>
     */
    public function setLoginDetail(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\Login\LoginDetail::class);
        $this->login_detail = $var;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.AddLoginActionResponse.Status status = 3;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.AddLoginActionResponse.Status status = 3;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\AddLoginActionResponse_Status::class);
        $this->status = $var;
    }

}

