<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/BelugaTransactionCompleteResponse.proto

namespace POGOProtos\Networking\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Responses\BelugaTransactionCompleteResponse\Status instead.
     * @deprecated
     */
    class BelugaTransactionCompleteResponse_Status {}
}
class_exists(BelugaTransactionCompleteResponse\Status::class);
@trigger_error('POGOProtos\Networking\Responses\BelugaTransactionCompleteResponse_Status is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Responses\BelugaTransactionCompleteResponse\Status instead', E_USER_DEPRECATED);

