<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/CheckChallengeResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Responses.CheckChallengeResponse</code>
 */
class CheckChallengeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool show_challenge = 1;</code>
     */
    private $show_challenge = false;
    /**
     * Generated from protobuf field <code>string challenge_url = 2;</code>
     */
    private $challenge_url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $show_challenge
     *     @type string $challenge_url
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Responses\CheckChallengeResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool show_challenge = 1;</code>
     * @return bool
     */
    public function getShowChallenge()
    {
        return $this->show_challenge;
    }

    /**
     * Generated from protobuf field <code>bool show_challenge = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setShowChallenge($var)
    {
        GPBUtil::checkBool($var);
        $this->show_challenge = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string challenge_url = 2;</code>
     * @return string
     */
    public function getChallengeUrl()
    {
        return $this->challenge_url;
    }

    /**
     * Generated from protobuf field <code>string challenge_url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChallengeUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->challenge_url = $var;

        return $this;
    }

}

