<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/ClaimCodenameResponse.proto

namespace POGOProtos\Networking\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Responses\ClaimCodenameResponse\Status instead.
     * @deprecated
     */
    class ClaimCodenameResponse_Status {}
}
class_exists(ClaimCodenameResponse\Status::class);
@trigger_error('POGOProtos\Networking\Responses\ClaimCodenameResponse_Status is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Responses\ClaimCodenameResponse\Status instead', E_USER_DEPRECATED);

