<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/ConfirmPhotobombResponse.proto

namespace POGOProtos\Networking\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Responses\ConfirmPhotobombResponse\Status instead.
     * @deprecated
     */
    class ConfirmPhotobombResponse_Status {}
}
class_exists(ConfirmPhotobombResponse\Status::class);
@trigger_error('POGOProtos\Networking\Responses\ConfirmPhotobombResponse_Status is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Responses\ConfirmPhotobombResponse\Status instead', E_USER_DEPRECATED);

