<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/FetchAllNewsResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Responses.FetchAllNewsResponse</code>
 */
class FetchAllNewsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.FetchAllNewsResponse.Result result = 1;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.News.CurrentNews current_news = 2;</code>
     */
    private $current_news = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $result
     *     @type \POGOProtos\Data\News\CurrentNews $current_news
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Responses\FetchAllNewsResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.FetchAllNewsResponse.Result result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.FetchAllNewsResponse.Result result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\FetchAllNewsResponse_Result::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.News.CurrentNews current_news = 2;</code>
     * @return \POGOProtos\Data\News\CurrentNews
     */
    public function getCurrentNews()
    {
        return $this->current_news;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.News.CurrentNews current_news = 2;</code>
     * @param \POGOProtos\Data\News\CurrentNews $var
     * @return $this
     */
    public function setCurrentNews($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\News\CurrentNews::class);
        $this->current_news = $var;

        return $this;
    }

}

