<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetAvailableSkusAndBalancesResponse.proto

namespace POGOProtos\Networking\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Responses\GetAvailableSkusAndBalancesResponse\Status instead.
     * @deprecated
     */
    class GetAvailableSkusAndBalancesResponse_Status {}
}
class_exists(GetAvailableSkusAndBalancesResponse\Status::class);
@trigger_error('POGOProtos\Networking\Responses\GetAvailableSkusAndBalancesResponse_Status is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Responses\GetAvailableSkusAndBalancesResponse\Status instead', E_USER_DEPRECATED);

