<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetMapObjectsResponse.proto

namespace POGOProtos\Networking\Responses;

/**
 * Protobuf enum <code>POGOProtos.Networking.Responses.GetMapObjectsResponse.TimeOfDay</code>
 */
class GetMapObjectsResponse_TimeOfDay
{
    /**
     * <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * <code>DAY = 1;</code>
     */
    const DAY = 1;
    /**
     * <code>NIGHT = 2;</code>
     */
    const NIGHT = 2;
}

