<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetNewQuestsResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.GetNewQuestsResponse</code>
 */
class GetNewQuestsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Responses.GetNewQuestsResponse.Status status = 1;</code>
     */
    private $status = 0;
    /**
     * <code>repeated .POGOProtos.Data.Quests.ClientQuest quests = 2;</code>
     */
    private $quests;
    /**
     * <code>repeated .POGOProtos.Data.Quests.ClientQuest version_changed_quests = 3;</code>
     */
    private $version_changed_quests;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\GetNewQuestsResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Responses.GetNewQuestsResponse.Status status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.GetNewQuestsResponse.Status status = 1;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\GetNewQuestsResponse_Status::class);
        $this->status = $var;
    }

    /**
     * <code>repeated .POGOProtos.Data.Quests.ClientQuest quests = 2;</code>
     */
    public function getQuests()
    {
        return $this->quests;
    }

    /**
     * <code>repeated .POGOProtos.Data.Quests.ClientQuest quests = 2;</code>
     */
    public function setQuests(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\Quests\ClientQuest::class);
        $this->quests = $var;
    }

    /**
     * <code>repeated .POGOProtos.Data.Quests.ClientQuest version_changed_quests = 3;</code>
     */
    public function getVersionChangedQuests()
    {
        return $this->version_changed_quests;
    }

    /**
     * <code>repeated .POGOProtos.Data.Quests.ClientQuest version_changed_quests = 3;</code>
     */
    public function setVersionChangedQuests(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\Quests\ClientQuest::class);
        $this->version_changed_quests = $var;
    }

}

