<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetPlayerProfileResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Responses.GetPlayerProfileResponse</code>
 */
class GetPlayerProfileResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.GetPlayerProfileResponse.Result result = 1;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>int64 start_time = 2;</code>
     */
    private $start_time = 0;
    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.PlayerBadge badges = 3;</code>
     */
    private $badges;
    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.GetPlayerProfileResponse.GymBadges gym_badges = 4;</code>
     */
    private $gym_badges = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $result
     *     @type int|string $start_time
     *     @type \POGOProtos\Data\PlayerBadge[]|\Google\Protobuf\Internal\RepeatedField $badges
     *     @type \POGOProtos\Networking\Responses\GetPlayerProfileResponse\GymBadges $gym_badges
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Responses\GetPlayerProfileResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.GetPlayerProfileResponse.Result result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.GetPlayerProfileResponse.Result result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\GetPlayerProfileResponse_Result::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 start_time = 2;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->start_time;
    }

    /**
     * Generated from protobuf field <code>int64 start_time = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.PlayerBadge badges = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getBadges()
    {
        return $this->badges;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.PlayerBadge badges = 3;</code>
     * @param \POGOProtos\Data\PlayerBadge[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setBadges($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\PlayerBadge::class);
        $this->badges = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.GetPlayerProfileResponse.GymBadges gym_badges = 4;</code>
     * @return \POGOProtos\Networking\Responses\GetPlayerProfileResponse\GymBadges
     */
    public function getGymBadges()
    {
        return $this->gym_badges;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.GetPlayerProfileResponse.GymBadges gym_badges = 4;</code>
     * @param \POGOProtos\Networking\Responses\GetPlayerProfileResponse\GymBadges $var
     * @return $this
     */
    public function setGymBadges($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Networking\Responses\GetPlayerProfileResponse_GymBadges::class);
        $this->gym_badges = $var;

        return $this;
    }

}

