<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/RegisterBackgroundDeviceResponse.proto

namespace POGOProtos\Networking\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Responses\RegisterBackgroundDeviceResponse\Status instead.
     * @deprecated
     */
    class RegisterBackgroundDeviceResponse_Status {}
}
class_exists(RegisterBackgroundDeviceResponse\Status::class);
@trigger_error('POGOProtos\Networking\Responses\RegisterBackgroundDeviceResponse_Status is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Responses\RegisterBackgroundDeviceResponse\Status instead', E_USER_DEPRECATED);

