<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/RegisterBackgroundDeviceResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Responses.RegisterBackgroundDeviceResponse</code>
 */
class RegisterBackgroundDeviceResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.RegisterBackgroundDeviceResponse.Status status = 1;</code>
     */
    private $status = 0;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.BackgroundToken token = 2;</code>
     */
    private $token = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $status
     *     @type \POGOProtos\Data\BackgroundToken $token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Responses\RegisterBackgroundDeviceResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.RegisterBackgroundDeviceResponse.Status status = 1;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.RegisterBackgroundDeviceResponse.Status status = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\RegisterBackgroundDeviceResponse_Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.BackgroundToken token = 2;</code>
     * @return \POGOProtos\Data\BackgroundToken
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.BackgroundToken token = 2;</code>
     * @param \POGOProtos\Data\BackgroundToken $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\BackgroundToken::class);
        $this->token = $var;

        return $this;
    }

}

