<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SubmitNewPoiResponse.proto

namespace POGOProtos\Networking\Responses;

/**
 * Protobuf enum <code>POGOProtos.Networking.Responses.SubmitNewPoiResponse.Status</code>
 */
class SubmitNewPoiResponse_Status
{
    /**
     * <code>UNSET = 0;</code>
     */
    const UNSET = 0;
    /**
     * <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
    /**
     * <code>FAILURE = 2;</code>
     */
    const FAILURE = 2;
    /**
     * <code>INTERNAL_ERROR = 3;</code>
     */
    const INTERNAL_ERROR = 3;
    /**
     * <code>TOO_MANY_RECENT_SUBMISSIONS = 4;</code>
     */
    const TOO_MANY_RECENT_SUBMISSIONS = 4;
}

