<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UnlockSpecialMoveResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Responses.UnlockSpecialMoveResponse</code>
 */
class UnlockSpecialMoveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.UnlockSpecialMoveResponse.Result result = 1;</code>
     */
    private $result = 0;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.PokemonData unlocked_pokemon = 2;</code>
     */
    private $unlocked_pokemon = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $result
     *     @type \POGOProtos\Data\PokemonData $unlocked_pokemon
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Responses\UnlockSpecialMoveResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.UnlockSpecialMoveResponse.Result result = 1;</code>
     * @return int
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Networking.Responses.UnlockSpecialMoveResponse.Result result = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\UnlockSpecialMoveResponse_Result::class);
        $this->result = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.PokemonData unlocked_pokemon = 2;</code>
     * @return \POGOProtos\Data\PokemonData
     */
    public function getUnlockedPokemon()
    {
        return $this->unlocked_pokemon;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.PokemonData unlocked_pokemon = 2;</code>
     * @param \POGOProtos\Data\PokemonData $var
     * @return $this
     */
    public function setUnlockedPokemon($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\PokemonData::class);
        $this->unlocked_pokemon = $var;

        return $this;
    }

}

