<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UpdateNotificationResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.UpdateNotificationResponse</code>
 */
class UpdateNotificationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated string notification_ids = 1;</code>
     */
    private $notification_ids;
    /**
     * <code>repeated int64 create_timestamp_ms = 2;</code>
     */
    private $create_timestamp_ms;
    /**
     * <code>.POGOProtos.Enums.NotificationState state = 3;</code>
     */
    private $state = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\UpdateNotificationResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated string notification_ids = 1;</code>
     */
    public function getNotificationIds()
    {
        return $this->notification_ids;
    }

    /**
     * <code>repeated string notification_ids = 1;</code>
     */
    public function setNotificationIds(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->notification_ids = $var;
    }

    /**
     * <code>repeated int64 create_timestamp_ms = 2;</code>
     */
    public function getCreateTimestampMs()
    {
        return $this->create_timestamp_ms;
    }

    /**
     * <code>repeated int64 create_timestamp_ms = 2;</code>
     */
    public function setCreateTimestampMs(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->create_timestamp_ms = $var;
    }

    /**
     * <code>.POGOProtos.Enums.NotificationState state = 3;</code>
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * <code>.POGOProtos.Enums.NotificationState state = 3;</code>
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\NotificationState::class);
        $this->state = $var;
    }

}

