<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UseItemCaptureResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Responses.UseItemCaptureResponse</code>
 */
class UseItemCaptureResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    private $success = false;
    /**
     * Generated from protobuf field <code>double item_capture_mult = 2;</code>
     */
    private $item_capture_mult = 0.0;
    /**
     * Generated from protobuf field <code>double item_flee_mult = 3;</code>
     */
    private $item_flee_mult = 0.0;
    /**
     * Generated from protobuf field <code>bool stop_movement = 4;</code>
     */
    private $stop_movement = false;
    /**
     * Generated from protobuf field <code>bool stop_attack = 5;</code>
     */
    private $stop_attack = false;
    /**
     * Generated from protobuf field <code>bool target_max = 6;</code>
     */
    private $target_max = false;
    /**
     * Generated from protobuf field <code>bool target_slow = 7;</code>
     */
    private $target_slow = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *     @type float $item_capture_mult
     *     @type float $item_flee_mult
     *     @type bool $stop_movement
     *     @type bool $stop_attack
     *     @type bool $target_max
     *     @type bool $target_slow
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Responses\UseItemCaptureResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double item_capture_mult = 2;</code>
     * @return float
     */
    public function getItemCaptureMult()
    {
        return $this->item_capture_mult;
    }

    /**
     * Generated from protobuf field <code>double item_capture_mult = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setItemCaptureMult($var)
    {
        GPBUtil::checkDouble($var);
        $this->item_capture_mult = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double item_flee_mult = 3;</code>
     * @return float
     */
    public function getItemFleeMult()
    {
        return $this->item_flee_mult;
    }

    /**
     * Generated from protobuf field <code>double item_flee_mult = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setItemFleeMult($var)
    {
        GPBUtil::checkDouble($var);
        $this->item_flee_mult = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool stop_movement = 4;</code>
     * @return bool
     */
    public function getStopMovement()
    {
        return $this->stop_movement;
    }

    /**
     * Generated from protobuf field <code>bool stop_movement = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setStopMovement($var)
    {
        GPBUtil::checkBool($var);
        $this->stop_movement = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool stop_attack = 5;</code>
     * @return bool
     */
    public function getStopAttack()
    {
        return $this->stop_attack;
    }

    /**
     * Generated from protobuf field <code>bool stop_attack = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setStopAttack($var)
    {
        GPBUtil::checkBool($var);
        $this->stop_attack = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool target_max = 6;</code>
     * @return bool
     */
    public function getTargetMax()
    {
        return $this->target_max;
    }

    /**
     * Generated from protobuf field <code>bool target_max = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setTargetMax($var)
    {
        GPBUtil::checkBool($var);
        $this->target_max = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool target_slow = 7;</code>
     * @return bool
     */
    public function getTargetSlow()
    {
        return $this->target_slow;
    }

    /**
     * Generated from protobuf field <code>bool target_slow = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setTargetSlow($var)
    {
        GPBUtil::checkBool($var);
        $this->target_slow = $var;

        return $this;
    }

}

