<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UseItemEncounterResponse.proto

namespace POGOProtos\Networking\Responses;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.UseItemEncounterResponse</code>
 */
class UseItemEncounterResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Responses.UseItemEncounterResponse.Status status = 1;</code>
     */
    private $status = 0;
    /**
     * <code>.POGOProtos.Data.Capture.CaptureProbability capture_probability = 2;</code>
     */
    private $capture_probability = null;
    /**
     * <code>.POGOProtos.Inventory.Item.ItemId active_item = 3;</code>
     */
    private $active_item = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Responses\UseItemEncounterResponse::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Responses.UseItemEncounterResponse.Status status = 1;</code>
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * <code>.POGOProtos.Networking.Responses.UseItemEncounterResponse.Status status = 1;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Networking\Responses\UseItemEncounterResponse_Status::class);
        $this->status = $var;
    }

    /**
     * <code>.POGOProtos.Data.Capture.CaptureProbability capture_probability = 2;</code>
     */
    public function getCaptureProbability()
    {
        return $this->capture_probability;
    }

    /**
     * <code>.POGOProtos.Data.Capture.CaptureProbability capture_probability = 2;</code>
     */
    public function setCaptureProbability(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Capture\CaptureProbability::class);
        $this->capture_probability = $var;
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId active_item = 3;</code>
     */
    public function getActiveItem()
    {
        return $this->active_item;
    }

    /**
     * <code>.POGOProtos.Inventory.Item.ItemId active_item = 3;</code>
     */
    public function setActiveItem($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Inventory\Item\ItemId::class);
        $this->active_item = $var;
    }

}

