<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Sfida/SfidaDowserRequest.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Sfida;

class SfidaDowserRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a99010a3d504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f53666964612f5366696461446f7773657252657175657374" .
            "2e70726f746f1224504f474f50726f746f732e4e6574776f726b696e672e" .
            "52657175657374732e5366696461222a0a125366696461446f7773657252" .
            "65717565737412140a0c656e636f756e7465725f69641801200128036206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

