<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Combat/PokemonCombatStats.proto

namespace POGOProtos\Data\Combat;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Combat.PokemonCombatStats</code>
 */
class PokemonCombatStats extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 num_won = 1;</code>
     */
    private $num_won = 0;
    /**
     * Generated from protobuf field <code>int32 num_total = 2;</code>
     */
    private $num_total = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $num_won
     *     @type int $num_total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Combat\PokemonCombatStats::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 num_won = 1;</code>
     * @return int
     */
    public function getNumWon()
    {
        return $this->num_won;
    }

    /**
     * Generated from protobuf field <code>int32 num_won = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNumWon($var)
    {
        GPBUtil::checkInt32($var);
        $this->num_won = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 num_total = 2;</code>
     * @return int
     */
    public function getNumTotal()
    {
        return $this->num_total;
    }

    /**
     * Generated from protobuf field <code>int32 num_total = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setNumTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->num_total = $var;

        return $this;
    }

}

