<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/RegisterDownstreamServerActionsResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Platform\Responses;

class RegisterDownstreamServerActionsResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5010a56504f474f50726f746f732f4e6574776f726b696e672f506c61" .
            "74666f726d2f526573706f6e7365732f5265676973746572446f776e7374" .
            "7265616d536572766572416374696f6e73526573706f6e73652e70726f74" .
            "6f1228504f474f50726f746f732e4e6574776f726b696e672e506c617466" .
            "6f726d2e526573706f6e73657322290a275265676973746572446f776e73" .
            "747265616d536572766572416374696f6e73526573706f6e736562067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

