<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/RemoveLoginActionResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Platform\Responses;

class RemoveLoginActionResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Login\LoginDetail::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aef020a48504f474f50726f746f732f4e6574776f726b696e672f506c61" .
            "74666f726d2f526573706f6e7365732f52656d6f76654c6f67696e416374" .
            "696f6e526573706f6e73652e70726f746f1228504f474f50726f746f732e" .
            "4e6574776f726b696e672e506c6174666f726d2e526573706f6e73657322" .
            "f0010a1952656d6f76654c6f67696e416374696f6e526573706f6e736512" .
            "0f0a077375636365737318012001280812380a0c6c6f67696e5f64657461" .
            "696c18022003280b32222e504f474f50726f746f732e446174612e4c6f67" .
            "696e2e4c6f67696e44657461696c125a0a0673746174757318032001280e" .
            "324a2e504f474f50726f746f732e4e6574776f726b696e672e506c617466" .
            "6f726d2e526573706f6e7365732e52656d6f76654c6f67696e416374696f" .
            "6e526573706f6e73652e537461747573222c0a0653746174757312090a05" .
            "554e534554100012170a134c4f47494e5f4e4f545f52454d4f5641424c45" .
            "1001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

