<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/UpdateNotificationStatusResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Platform\Responses;

class UpdateNotificationStatusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\NotificationState::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a93020a4f504f474f50726f746f732f4e6574776f726b696e672f506c61" .
            "74666f726d2f526573706f6e7365732f5570646174654e6f746966696361" .
            "74696f6e537461747573526573706f6e73652e70726f746f1228504f474f" .
            "50726f746f732e4e6574776f726b696e672e506c6174666f726d2e526573" .
            "706f6e736573228d010a205570646174654e6f74696669636174696f6e53" .
            "7461747573526573706f6e736512180a106e6f74696669636174696f6e5f" .
            "696473180120032809121b0a136372656174655f74696d657374616d705f" .
            "6d7318022003280312320a05737461746518032001280e32232e504f474f" .
            "50726f746f732e456e756d732e4e6f74696669636174696f6e5374617465" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

