<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Fitness/FitnessMetricsReportHistory.proto

namespace GPBMetadata\POGOProtos\Data\Fitness;

class FitnessMetricsReportHistory
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Fitness\FitnessMetrics::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91030a39504f474f50726f746f732f446174612f4669746e6573732f46" .
            "69746e6573734d6574726963735265706f7274486973746f72792e70726f" .
            "746f1217504f474f50726f746f732e446174612e4669746e65737322b202" .
            "0a1b4669746e6573734d6574726963735265706f7274486973746f727912" .
            "5b0a0e7765656b6c795f686973746f727918012003280b32432e504f474f" .
            "50726f746f732e446174612e4669746e6573732e4669746e6573734d6574" .
            "726963735265706f7274486973746f72792e4d657472696373486973746f" .
            "7279125a0a0d6461696c795f686973746f727918022003280b32432e504f" .
            "474f50726f746f732e446174612e4669746e6573732e4669746e6573734d" .
            "6574726963735265706f7274486973746f72792e4d657472696373486973" .
            "746f72791a5a0a0e4d657472696373486973746f7279120e0a066275636b" .
            "657418012001280312380a076d65747269637318022001280b32272e504f" .
            "474f50726f746f732e446174612e4669746e6573732e4669746e6573734d" .
            "657472696373620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

