<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/OnboardingSettings.proto

namespace GPBMetadata\POGOProtos\Settings\Master;

class OnboardingSettings
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad5010a33504f474f50726f746f732f53657474696e67732f4d61737465" .
            "722f4f6e626f617264696e6753657474696e67732e70726f746f121a504f" .
            "474f50726f746f732e53657474696e67732e4d6173746572227a0a124f6e" .
            "626f617264696e6753657474696e677312210a19736b69705f6176617461" .
            "725f637573746f6d697a6174696f6e18012001280812210a196469736162" .
            "6c655f696e697469616c5f61725f70726f6d7074180220012808121e0a16" .
            "61725f70726f6d70745f706c617965725f6c6576656c18032001280d6206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

