<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/BuyItemPokeCoinsResponse.proto

namespace POGOProtos\Networking\Platform\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse\Status instead.
     * @deprecated
     */
    class BuyItemPokeCoinsResponse_Status {}
}
class_exists(BuyItemPokeCoinsResponse\Status::class);
@trigger_error('POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse_Status is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Platform\Responses\BuyItemPokeCoinsResponse\Status instead', E_USER_DEPRECATED);

