<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/GetAvailableSkusAndBalancesResponse.proto

namespace POGOProtos\Networking\Platform\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Platform\Responses\GetAvailableSkusAndBalancesResponse\AvailableSku instead.
     * @deprecated
     */
    class GetAvailableSkusAndBalancesResponse_AvailableSku {}
}
class_exists(GetAvailableSkusAndBalancesResponse\AvailableSku::class);
@trigger_error('POGOProtos\Networking\Platform\Responses\GetAvailableSkusAndBalancesResponse_AvailableSku is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Platform\Responses\GetAvailableSkusAndBalancesResponse\AvailableSku instead', E_USER_DEPRECATED);

