<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/GetAvailableSkusAndBalancesResponse.proto

namespace POGOProtos\Networking\Platform\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Platform\Responses\GetAvailableSkusAndBalancesResponse\GameItemContent instead.
     * @deprecated
     */
    class GetAvailableSkusAndBalancesResponse_GameItemContent {}
}
class_exists(GetAvailableSkusAndBalancesResponse\GameItemContent::class);
@trigger_error('POGOProtos\Networking\Platform\Responses\GetAvailableSkusAndBalancesResponse_GameItemContent is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Platform\Responses\GetAvailableSkusAndBalancesResponse\GameItemContent instead', E_USER_DEPRECATED);

