<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/PurchaseSkuResponse.proto

namespace POGOProtos\Networking\Platform\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Platform\Responses\PurchaseSkuResponse\Status instead.
     * @deprecated
     */
    class PurchaseSkuResponse_Status {}
}
class_exists(PurchaseSkuResponse\Status::class);
@trigger_error('POGOProtos\Networking\Platform\Responses\PurchaseSkuResponse_Status is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Platform\Responses\PurchaseSkuResponse\Status instead', E_USER_DEPRECATED);

