<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/UpdateFitnessMetricsResponse.proto

namespace POGOProtos\Networking\Platform\Responses;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Platform\Responses\UpdateFitnessMetricsResponse\Status instead.
     * @deprecated
     */
    class UpdateFitnessMetricsResponse_Status {}
}
class_exists(UpdateFitnessMetricsResponse\Status::class);
@trigger_error('POGOProtos\Networking\Platform\Responses\UpdateFitnessMetricsResponse_Status is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Platform\Responses\UpdateFitnessMetricsResponse\Status instead', E_USER_DEPRECATED);

