<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Inventory/EggIncubators.proto

namespace POGOProtos\Inventory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Inventory.EggIncubators</code>
 */
class EggIncubators extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Inventory.EggIncubator egg_incubator = 1;</code>
     */
    private $egg_incubator;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \POGOProtos\Inventory\EggIncubator[]|\Google\Protobuf\Internal\RepeatedField $egg_incubator
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Inventory\EggIncubators::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Inventory.EggIncubator egg_incubator = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEggIncubator()
    {
        return $this->egg_incubator;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Inventory.EggIncubator egg_incubator = 1;</code>
     * @param \POGOProtos\Inventory\EggIncubator[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEggIncubator($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Inventory\EggIncubator::class);
        $this->egg_incubator = $arr;

        return $this;
    }

}

