<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/CatchPokemonQuest.proto

namespace GPBMetadata\POGOProtos\Data\Quests;

class CatchPokemonQuest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a650a2e504f474f50726f746f732f446174612f5175657374732f436174" .
            "6368506f6b656d6f6e51756573742e70726f746f1216504f474f50726f74" .
            "6f732e446174612e51756573747322130a114361746368506f6b656d6f6e" .
            "5175657374620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

