<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Sfida/SfidaMetricsUpdate.proto

namespace POGOProtos\Data\Sfida;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Sfida.SfidaMetricsUpdate</code>
 */
class SfidaMetricsUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Sfida.SfidaMetricsUpdate.UpdateType update_type = 1;</code>
     */
    private $update_type = 0;
    /**
     * Generated from protobuf field <code>int64 timestamp_ms = 2;</code>
     */
    private $timestamp_ms = 0;
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Sfida.SfidaMetrics metrics = 3;</code>
     */
    private $metrics = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $update_type
     *     @type int|string $timestamp_ms
     *     @type \POGOProtos\Data\Sfida\SfidaMetrics $metrics
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Sfida\SfidaMetricsUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Sfida.SfidaMetricsUpdate.UpdateType update_type = 1;</code>
     * @return int
     */
    public function getUpdateType()
    {
        return $this->update_type;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Sfida.SfidaMetricsUpdate.UpdateType update_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setUpdateType($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Data\Sfida\SfidaMetricsUpdate_UpdateType::class);
        $this->update_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp_ms = 2;</code>
     * @return int|string
     */
    public function getTimestampMs()
    {
        return $this->timestamp_ms;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp_ms = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestampMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Sfida.SfidaMetrics metrics = 3;</code>
     * @return \POGOProtos\Data\Sfida\SfidaMetrics
     */
    public function getMetrics()
    {
        return $this->metrics;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Sfida.SfidaMetrics metrics = 3;</code>
     * @param \POGOProtos\Data\Sfida\SfidaMetrics $var
     * @return $this
     */
    public function setMetrics($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Sfida\SfidaMetrics::class);
        $this->metrics = $var;

        return $this;
    }

}

