<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Telemetry/PlatformDataId.proto

namespace GPBMetadata\POGOProtos\Networking\Platform\Telemetry;

class PlatformDataId
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Networking\Platform\Telemetry\TelemetryDomainId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af4010a3d504f474f50726f746f732f4e6574776f726b696e672f506c61" .
            "74666f726d2f54656c656d657472792f506c6174666f726d446174614964" .
            "2e70726f746f1228504f474f50726f746f732e4e6574776f726b696e672e" .
            "506c6174666f726d2e54656c656d657472792280010a0e506c6174666f72" .
            "6d44617461496412140a0c74656c656d657472795f696418012001280512" .
            "580a1374656c656d657472795f646f6d61696e5f696418022001280e323b" .
            "2e504f474f50726f746f732e4e6574776f726b696e672e506c6174666f72" .
            "6d2e54656c656d657472792e54656c656d65747279446f6d61696e496462" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

