<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/FortRenderingType.proto

namespace POGOProtos\Map\Fort;

/**
 * Protobuf type <code>POGOProtos.Map.Fort.FortRenderingType</code>
 */
class FortRenderingType
{
    /**
     * Generated from protobuf enum <code>DEFAULT = 0;</code>
     */
    const PBDEFAULT = 0;
    /**
     * Generated from protobuf enum <code>INTERNAL_TEST = 1;</code>
     */
    const INTERNAL_TEST = 1;
}

