<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/GymDisplay.proto

namespace POGOProtos\Map\Fort;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Map.Fort.GymDisplay</code>
 */
class GymDisplay extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .POGOProtos.Map.Fort.GymEvent gym_event = 1;</code>
     */
    private $gym_event;
    /**
     * <code>int32 total_gym_cp = 2;</code>
     */
    private $total_gym_cp = 0;
    /**
     * <code>double lowest_pokemon_motivation = 3;</code>
     */
    private $lowest_pokemon_motivation = 0.0;
    /**
     * <code>int32 slots_available = 4;</code>
     */
    private $slots_available = 0;
    /**
     * <code>int64 occupied_millis = 5;</code>
     */
    private $occupied_millis = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Map\Fort\GymDisplay::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .POGOProtos.Map.Fort.GymEvent gym_event = 1;</code>
     */
    public function getGymEvent()
    {
        return $this->gym_event;
    }

    /**
     * <code>repeated .POGOProtos.Map.Fort.GymEvent gym_event = 1;</code>
     */
    public function setGymEvent(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Map\Fort\GymEvent::class);
        $this->gym_event = $var;
    }

    /**
     * <code>int32 total_gym_cp = 2;</code>
     */
    public function getTotalGymCp()
    {
        return $this->total_gym_cp;
    }

    /**
     * <code>int32 total_gym_cp = 2;</code>
     */
    public function setTotalGymCp($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_gym_cp = $var;
    }

    /**
     * <code>double lowest_pokemon_motivation = 3;</code>
     */
    public function getLowestPokemonMotivation()
    {
        return $this->lowest_pokemon_motivation;
    }

    /**
     * <code>double lowest_pokemon_motivation = 3;</code>
     */
    public function setLowestPokemonMotivation($var)
    {
        GPBUtil::checkDouble($var);
        $this->lowest_pokemon_motivation = $var;
    }

    /**
     * <code>int32 slots_available = 4;</code>
     */
    public function getSlotsAvailable()
    {
        return $this->slots_available;
    }

    /**
     * <code>int32 slots_available = 4;</code>
     */
    public function setSlotsAvailable($var)
    {
        GPBUtil::checkInt32($var);
        $this->slots_available = $var;
    }

    /**
     * <code>int64 occupied_millis = 5;</code>
     */
    public function getOccupiedMillis()
    {
        return $this->occupied_millis;
    }

    /**
     * <code>int64 occupied_millis = 5;</code>
     */
    public function setOccupiedMillis($var)
    {
        GPBUtil::checkInt64($var);
        $this->occupied_millis = $var;
    }

}

