<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Fort/GymDisplay.proto

namespace POGOProtos\Map\Fort;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Map.Fort.GymDisplay</code>
 */
class GymDisplay extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Map.Fort.GymEvent gym_event = 1;</code>
     */
    private $gym_event;
    /**
     * Generated from protobuf field <code>int32 total_gym_cp = 2;</code>
     */
    private $total_gym_cp = 0;
    /**
     * Generated from protobuf field <code>double lowest_pokemon_motivation = 3;</code>
     */
    private $lowest_pokemon_motivation = 0.0;
    /**
     * Generated from protobuf field <code>int32 slots_available = 4;</code>
     */
    private $slots_available = 0;
    /**
     * Generated from protobuf field <code>int64 occupied_millis = 5;</code>
     */
    private $occupied_millis = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \POGOProtos\Map\Fort\GymEvent[]|\Google\Protobuf\Internal\RepeatedField $gym_event
     *     @type int $total_gym_cp
     *     @type float $lowest_pokemon_motivation
     *     @type int $slots_available
     *     @type int|string $occupied_millis
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Map\Fort\GymDisplay::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Map.Fort.GymEvent gym_event = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGymEvent()
    {
        return $this->gym_event;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Map.Fort.GymEvent gym_event = 1;</code>
     * @param \POGOProtos\Map\Fort\GymEvent[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGymEvent($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Map\Fort\GymEvent::class);
        $this->gym_event = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_gym_cp = 2;</code>
     * @return int
     */
    public function getTotalGymCp()
    {
        return $this->total_gym_cp;
    }

    /**
     * Generated from protobuf field <code>int32 total_gym_cp = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalGymCp($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_gym_cp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double lowest_pokemon_motivation = 3;</code>
     * @return float
     */
    public function getLowestPokemonMotivation()
    {
        return $this->lowest_pokemon_motivation;
    }

    /**
     * Generated from protobuf field <code>double lowest_pokemon_motivation = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setLowestPokemonMotivation($var)
    {
        GPBUtil::checkDouble($var);
        $this->lowest_pokemon_motivation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 slots_available = 4;</code>
     * @return int
     */
    public function getSlotsAvailable()
    {
        return $this->slots_available;
    }

    /**
     * Generated from protobuf field <code>int32 slots_available = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setSlotsAvailable($var)
    {
        GPBUtil::checkInt32($var);
        $this->slots_available = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 occupied_millis = 5;</code>
     * @return int|string
     */
    public function getOccupiedMillis()
    {
        return $this->occupied_millis;
    }

    /**
     * Generated from protobuf field <code>int64 occupied_millis = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOccupiedMillis($var)
    {
        GPBUtil::checkInt64($var);
        $this->occupied_millis = $var;

        return $this;
    }

}

