<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Logs/CompleteQuestStampCardLogEntry.proto

namespace GPBMetadata\POGOProtos\Data\Logs;

class CompleteQuestStampCardLogEntry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Quests\QuestReward::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa0020a39504f474f50726f746f732f446174612f4c6f67732f436f6d70" .
            "6c65746551756573745374616d70436172644c6f67456e7472792e70726f" .
            "746f1214504f474f50726f746f732e446174612e4c6f677322c4010a1e43" .
            "6f6d706c65746551756573745374616d70436172644c6f67456e74727912" .
            "4b0a06726573756c7418012001280e323b2e504f474f50726f746f732e44" .
            "6174612e4c6f67732e436f6d706c65746551756573745374616d70436172" .
            "644c6f67456e7472792e526573756c7412330a0672657761726418022003" .
            "280b32232e504f474f50726f746f732e446174612e5175657374732e5175" .
            "65737452657761726422200a06526573756c7412090a05554e5345541000" .
            "120b0a07535543434553531001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

