<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Telemetry/AssetStreamCacheCulledTelemetry.proto

namespace GPBMetadata\POGOProtos\Data\Telemetry;

class AssetStreamCacheCulledTelemetry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\TelemetryIds::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0adc010a3f504f474f50726f746f732f446174612f54656c656d65747279" .
            "2f417373657453747265616d436163686543756c6c656454656c656d6574" .
            "72792e70726f746f1219504f474f50726f746f732e446174612e54656c65" .
            "6d6574727922760a1f417373657453747265616d436163686543756c6c65" .
            "6454656c656d65747279123b0a0e61737365745f6576656e745f69641801" .
            "2001280e32232e504f474f50726f746f732e456e756d732e417373657454" .
            "656c656d6574727949647312160a0e73706163655f72656c656173656418" .
            "022001280d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

