<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Telemetry/FavoritePokemonTelemetry.proto

namespace GPBMetadata\POGOProtos\Data\Telemetry;

class FavoritePokemonTelemetry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Telemetry\PokemonTelemetry::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8010a38504f474f50726f746f732f446174612f54656c656d65747279" .
            "2f4661766f72697465506f6b656d6f6e54656c656d657472792e70726f74" .
            "6f1219504f474f50726f746f732e446174612e54656c656d657472792269" .
            "0a184661766f72697465506f6b656d6f6e54656c656d65747279123c0a07" .
            "706f6b656d6f6e18012001280b322b2e504f474f50726f746f732e446174" .
            "612e54656c656d657472792e506f6b656d6f6e54656c656d65747279120f" .
            "0a076661766f726564180220012808620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

