<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Social/GetGiftBoxDetailsMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Social;

class GetGiftBoxDetailsMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab8010a44504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f536f6369616c2f47657447696674426f7844657461696c73" .
            "4d6573736167652e70726f746f1225504f474f50726f746f732e4e657477" .
            "6f726b696e672e52657175657374732e536f6369616c22410a1847657447" .
            "696674426f7844657461696c734d65737361676512120a0a67696674626f" .
            "785f696418012003280412110a09706c617965725f696418022001280962" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

