<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Social/GetUploadUrlMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Social;

class GetUploadUrlMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab0010a3f504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f536f6369616c2f47657455706c6f616455726c4d65737361" .
            "67652e70726f746f1225504f474f50726f746f732e4e6574776f726b696e" .
            "672e52657175657374732e536f6369616c223e0a1347657455706c6f6164" .
            "55726c4d657373616765120f0a07757365725f696418012001280912160a" .
            "0e67616d655f756e697175655f6964180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

