<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Social/RemoveFriendMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Social;

class RemoveFriendMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a010a3f504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f536f6369616c2f52656d6f7665467269656e644d65737361" .
            "67652e70726f746f1225504f474f50726f746f732e4e6574776f726b696e" .
            "672e52657175657374732e536f6369616c22280a1352656d6f7665467269" .
            "656e644d65737361676512110a09706c617965725f696418012001280962" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

