<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Social/SetFriendNicknameMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Social;

class SetFriendNicknameMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0abd010a44504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f536f6369616c2f536574467269656e644e69636b6e616d65" .
            "4d6573736167652e70726f746f1225504f474f50726f746f732e4e657477" .
            "6f726b696e672e52657175657374732e536f6369616c22460a1853657446" .
            "7269656e644e69636b6e616d654d65737361676512110a09667269656e64" .
            "5f696418012001280912170a0f667269656e645f6e69636b6e616d651802" .
            "20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

