<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Requests/RegisterPushNotificationMessage.proto

namespace POGOProtos\Networking\Platform\Requests;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Platform\Requests\RegisterPushNotificationMessage\ApnToken instead.
     * @deprecated
     */
    class RegisterPushNotificationMessage_ApnToken {}
}
class_exists(RegisterPushNotificationMessage\ApnToken::class);
@trigger_error('POGOProtos\Networking\Platform\Requests\RegisterPushNotificationMessage_ApnToken is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Platform\Requests\RegisterPushNotificationMessage\ApnToken instead', E_USER_DEPRECATED);

