<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/AddFortModifierResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class AddFortModifierResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Networking\Responses\FortDetailsResponse::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad030a3d504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f416464466f72744d6f646966696572526573706f6e7365" .
            "2e70726f746f121f504f474f50726f746f732e4e6574776f726b696e672e" .
            "526573706f6e73657322c2020a17416464466f72744d6f64696669657252" .
            "6573706f6e7365124f0a06726573756c7418012001280e323f2e504f474f" .
            "50726f746f732e4e6574776f726b696e672e526573706f6e7365732e4164" .
            "64466f72744d6f646966696572526573706f6e73652e526573756c74124a" .
            "0a0c666f72745f64657461696c7318022001280b32342e504f474f50726f" .
            "746f732e4e6574776f726b696e672e526573706f6e7365732e466f727444" .
            "657461696c73526573706f6e73652289010a06526573756c7412110a0d4e" .
            "4f5f524553554c545f5345541000120b0a07535543434553531001121d0a" .
            "19464f52545f414c52454144595f4841535f4d4f44494649455210021210" .
            "0a0c544f4f5f4641525f41574159100312180a144e4f5f4954454d5f494e" .
            "5f494e56454e544f5259100412140a10504f495f494e4143434553534942" .
            "4c451005620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

