<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/ChangeTeamResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class ChangeTeamResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\PlayerData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afc020a38504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f4368616e67655465616d526573706f6e73652e70726f74" .
            "6f121f504f474f50726f746f732e4e6574776f726b696e672e526573706f" .
            "6e7365732296020a124368616e67655465616d526573706f6e7365124a0a" .
            "0673746174757318012001280e323a2e504f474f50726f746f732e4e6574" .
            "776f726b696e672e526573706f6e7365732e4368616e67655465616d5265" .
            "73706f6e73652e53746174757312330a0e757064617465645f706c617965" .
            "7218022001280b321b2e504f474f50726f746f732e446174612e506c6179" .
            "657244617461227f0a0653746174757312090a05554e5345541000120b0a" .
            "0753554343455353100112130a0f4552524f525f53414d455f5445414d10" .
            "02121f0a1b4552524f525f4954454d5f4e4f545f494e5f494e56454e544f" .
            "5259100312140a104552524f525f57524f4e475f4954454d100412110a0d" .
            "4552524f525f554e4b4e4f574e1005620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

