<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/DeclineCombatChallengeResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class DeclineCombatChallengeResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88030a44504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f4465636c696e65436f6d6261744368616c6c656e676552" .
            "6573706f6e73652e70726f746f121f504f474f50726f746f732e4e657477" .
            "6f726b696e672e526573706f6e7365732296020a1e4465636c696e65436f" .
            "6d6261744368616c6c656e6765526573706f6e736512560a06726573756c" .
            "7418012001280e32462e504f474f50726f746f732e4e6574776f726b696e" .
            "672e526573706f6e7365732e4465636c696e65436f6d6261744368616c6c" .
            "656e6765526573706f6e73652e526573756c74229b010a06526573756c74" .
            "12090a05554e5345541000120b0a0753554343455353100112210a1d4552" .
            "524f525f494e56414c49445f4348414c4c454e47455f5354415445100212" .
            "1d0a194552524f525f4348414c4c454e47455f4e4f545f464f554e441003" .
            "121a0a164552524f525f414c52454144595f54494d45444f55541004121b" .
            "0a174552524f525f414c52454144595f43414e43454c4c45441005620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

