<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/DeleteGiftResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class DeleteGiftResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aed020a38504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f44656c65746547696674526573706f6e73652e70726f74" .
            "6f121f504f474f50726f746f732e4e6574776f726b696e672e526573706f" .
            "6e7365732287020a1244656c65746547696674526573706f6e7365124a0a" .
            "06726573756c7418012001280e323a2e504f474f50726f746f732e4e6574" .
            "776f726b696e672e526573706f6e7365732e44656c657465476966745265" .
            "73706f6e73652e526573756c7422a4010a06526573756c7412090a05554e" .
            "5345541000120b0a0753554343455353100112110a0d4552524f525f554e" .
            "4b4e4f574e1002121b0a174552524f525f494e56414c49445f504c415945" .
            "525f49441003121a0a164552524f525f465249454e445f4e4f545f464f55" .
            "4e441004121d0a194552524f525f474946545f444f45535f4e4f545f4558" .
            "495354100512170a134552524f525f465249454e445f5550444154451006" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

