<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetInboxResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class GetInboxResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Inbox\ClientInbox::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab1020a36504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f476574496e626f78526573706f6e73652e70726f746f12" .
            "1f504f474f50726f746f732e4e6574776f726b696e672e526573706f6e73" .
            "657322cd010a10476574496e626f78526573706f6e736512480a06726573" .
            "756c7418012001280e32382e504f474f50726f746f732e4e6574776f726b" .
            "696e672e526573706f6e7365732e476574496e626f78526573706f6e7365" .
            "2e526573756c7412310a05696e626f7818022001280b32222e504f474f50" .
            "726f746f732e446174612e496e626f782e436c69656e74496e626f78223c" .
            "0a06526573756c7412090a05554e5345541000120b0a0753554343455353" .
            "1001120b0a074641494c5552451002120d0a0954494d45445f4f55541003" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

