<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetQuestDetailsResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class GetQuestDetailsResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Quests\ClientQuest::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8c030a3d504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f476574517565737444657461696c73526573706f6e7365" .
            "2e70726f746f121f504f474f50726f746f732e4e6574776f726b696e672e" .
            "526573706f6e7365731a28504f474f50726f746f732f446174612f517565" .
            "7374732f436c69656e7451756573742e70726f746f22f7010a1747657451" .
            "7565737444657461696c73526573706f6e7365124f0a0673746174757318" .
            "012001280e323f2e504f474f50726f746f732e4e6574776f726b696e672e" .
            "526573706f6e7365732e476574517565737444657461696c73526573706f" .
            "6e73652e53746174757312330a0671756573747318022003280b32232e50" .
            "4f474f50726f746f732e446174612e5175657374732e436c69656e745175" .
            "65737422560a0653746174757312090a05554e5345541000120b0a075355" .
            "4343455353100112190a154552524f525f51554553545f4e4f545f464f55" .
            "4e44100212190a154552524f525f494e56414c49445f444953504c415910" .
            "03620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

