<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/GetTutorialEggActionResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class GetTutorialEggActionResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae5020a42504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f4765745475746f7269616c456767416374696f6e526573" .
            "706f6e73652e70726f746f121f504f474f50726f746f732e4e6574776f72" .
            "6b696e672e526573706f6e73657322f5010a1c4765745475746f7269616c" .
            "456767416374696f6e526573706f6e736512540a06726573756c74180120" .
            "01280e32442e504f474f50726f746f732e4e6574776f726b696e672e5265" .
            "73706f6e7365732e4765745475746f7269616c456767416374696f6e5265" .
            "73706f6e73652e526573756c74227f0a06526573756c7412090a05554e53" .
            "45541000120b0a0753554343455353100112290a254552524f525f504c41" .
            "5945525f414c52454144595f4841535f5455544f5249414c5f4547471002" .
            "121b0a174552524f525f4641494c45445f544f5f4144445f454747100312" .
            "150a114552524f525f4e4f545f56325f464c4f571004620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

