<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/PushNotificationRegistryResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class PushNotificationRegistryResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa1020a46504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f507573684e6f74696669636174696f6e52656769737472" .
            "79526573706f6e73652e70726f746f121f504f474f50726f746f732e4e65" .
            "74776f726b696e672e526573706f6e73657322ad010a20507573684e6f74" .
            "696669636174696f6e5265676973747279526573706f6e736512580a0672" .
            "6573756c7418012001280e32482e504f474f50726f746f732e4e6574776f" .
            "726b696e672e526573706f6e7365732e507573684e6f7469666963617469" .
            "6f6e5265676973747279526573706f6e73652e526573756c74222f0a0652" .
            "6573756c7412090a05554e5345541000120b0a0753554343455353100112" .
            "0d0a094e4f5f4348414e47451002620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

