<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SetInGameCurrencyExchangeRateResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class SetInGameCurrencyExchangeRateResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae020a4b504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f536574496e47616d6543757272656e637945786368616e" .
            "676552617465526573706f6e73652e70726f746f121f504f474f50726f74" .
            "6f732e4e6574776f726b696e672e526573706f6e73657322b5010a255365" .
            "74496e47616d6543757272656e637945786368616e676552617465526573" .
            "706f6e7365125d0a0673746174757318012001280e324d2e504f474f5072" .
            "6f746f732e4e6574776f726b696e672e526573706f6e7365732e53657449" .
            "6e47616d6543757272656e637945786368616e676552617465526573706f" .
            "6e73652e537461747573222d0a0653746174757312090a05554e53455410" .
            "00120b0a07535543434553531001120b0a074641494c5552451002620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

