<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/SfidaCertificationResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class SfidaCertificationResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a010a40504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f536669646143657274696669636174696f6e526573706f" .
            "6e73652e70726f746f121f504f474f50726f746f732e4e6574776f726b69" .
            "6e672e526573706f6e736573222d0a1a5366696461436572746966696361" .
            "74696f6e526573706f6e7365120f0a077061796c6f616418012001280c62" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

