<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UpdatePlayerLocationResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class UpdatePlayerLocationResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8d010a42504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f557064617465506c617965724c6f636174696f6e526573" .
            "706f6e73652e70726f746f121f504f474f50726f746f732e4e6574776f72" .
            "6b696e672e526573706f6e736573221e0a1c557064617465506c61796572" .
            "4c6f636174696f6e526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

