<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/UpgradePokemonResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses;

class UpgradePokemonResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\PokemonData::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae9030a3c504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f55706772616465506f6b656d6f6e526573706f6e73652e" .
            "70726f746f121f504f474f50726f746f732e4e6574776f726b696e672e52" .
            "6573706f6e73657322ff020a1655706772616465506f6b656d6f6e526573" .
            "706f6e7365124e0a06726573756c7418012001280e323e2e504f474f5072" .
            "6f746f732e4e6574776f726b696e672e526573706f6e7365732e55706772" .
            "616465506f6b656d6f6e526573706f6e73652e526573756c7412360a1075" .
            "706772616465645f706f6b656d6f6e18022001280b321c2e504f474f5072" .
            "6f746f732e446174612e506f6b656d6f6e44617461123b0a156e6578745f" .
            "75706772616465645f706f6b656d6f6e18032001280b321c2e504f474f50" .
            "726f746f732e446174612e506f6b656d6f6e44617461229f010a06526573" .
            "756c7412090a05554e5345541000120b0a07535543434553531001121b0a" .
            "174552524f525f504f4b454d4f4e5f4e4f545f464f554e44100212200a1c" .
            "4552524f525f494e53554646494349454e545f5245534f55524345531003" .
            "121f0a1b4552524f525f555047524144455f4e4f545f415641494c41424c" .
            "451004121d0a194552524f525f504f4b454d4f4e5f49535f4445504c4f59" .
            "45441005620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

