<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Friends/FriendshipLevelData.proto

namespace GPBMetadata\POGOProtos\Data\Friends;

class FriendshipLevelData
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\FriendshipLevelMilestone::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb030a31504f474f50726f746f732f446174612f467269656e64732f46" .
            "7269656e64736869704c6576656c446174612e70726f746f1217504f474f" .
            "50726f746f732e446174612e467269656e64731a2f504f474f50726f746f" .
            "732f456e756d732f467269656e64736869704c6576656c4d696c6573746f" .
            "6e652e70726f746f22c3020a13467269656e64736869704c6576656c4461" .
            "7461120e0a066275636b6574180120012803121b0a13706f696e74735f65" .
            "61726e65645f746f64617918022001280512500a1c617761726465645f66" .
            "7269656e64736869705f6d696c6573746f6e6518032001280e322a2e504f" .
            "474f50726f746f732e456e756d732e467269656e64736869704c6576656c" .
            "4d696c6573746f6e6512500a1c63757272656e745f667269656e64736869" .
            "705f6d696c6573746f6e6518042001280e322a2e504f474f50726f746f73" .
            "2e456e756d732e467269656e64736869704c6576656c4d696c6573746f6e" .
            "6512350a2d6e6578745f667269656e64736869705f6d696c6573746f6e65" .
            "5f70726f67726573735f70657263656e7461676518052001280112240a1c" .
            "706f696e74735f746f776172645f6e6578745f6d696c6573746f6e651806" .
            "20012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

