<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Combat/ChallengePlayer.proto

namespace GPBMetadata\POGOProtos\Data\Combat;

class ChallengePlayer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Player\PlayerAvatar::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af2010a2c504f474f50726f746f732f446174612f436f6d6261742f4368" .
            "616c6c656e6765506c617965722e70726f746f1216504f474f50726f746f" .
            "732e446174612e436f6d62617422a1010a0f4368616c6c656e6765506c61" .
            "79657212110a09706c617965725f6964180120012809123b0a0d706c6179" .
            "65725f61766174617218022001280b32242e504f474f50726f746f732e44" .
            "6174612e506c617965722e506c6179657241766174617212200a18636f6d" .
            "6261745f706c617965725f73325f63656c6c5f6964180320012803121c0a" .
            "1461747461636b696e675f706f6b656d6f6e5f6964180420032806620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

