<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Combat/CombatPlayer.proto

namespace GPBMetadata\POGOProtos\Data\Combat;

class CombatPlayer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Player\PlayerPublicProfile::initOnce();
        \GPBMetadata\POGOProtos\Data\Combat\CombatPokemon::initOnce();
        \GPBMetadata\POGOProtos\Data\Combat\CombatAction::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad050a29504f474f50726f746f732f446174612f436f6d6261742f436f" .
            "6d626174506c617965722e70726f746f1216504f474f50726f746f732e44" .
            "6174612e436f6d6261741a2a504f474f50726f746f732f446174612f436f" .
            "6d6261742f436f6d626174506f6b656d6f6e2e70726f746f1a29504f474f" .
            "50726f746f732f446174612f436f6d6261742f436f6d626174416374696f" .
            "6e2e70726f746f2288040a0c436f6d626174506c6179657212430a0e7075" .
            "626c69635f70726f66696c6518012001280b322b2e504f474f50726f746f" .
            "732e446174612e506c617965722e506c617965725075626c696350726f66" .
            "696c65123d0a0e6163746976655f706f6b656d6f6e18022001280b32252e" .
            "504f474f50726f746f732e446174612e436f6d6261742e436f6d62617450" .
            "6f6b656d6f6e123e0a0f726573657276655f706f6b656d6f6e1803200328" .
            "0b32252e504f474f50726f746f732e446174612e436f6d6261742e436f6d" .
            "626174506f6b656d6f6e123e0a0f6661696e7465645f706f6b656d6f6e18" .
            "042003280b32252e504f474f50726f746f732e446174612e436f6d626174" .
            "2e436f6d626174506f6b656d6f6e123c0a0e63757272656e745f61637469" .
            "6f6e18052001280b32242e504f474f50726f746f732e446174612e436f6d" .
            "6261742e436f6d626174416374696f6e12140a0c6c6f636b737465705f61" .
            "636b18062001280812190a116c6173745f757064617465645f7475726e18" .
            "0720012805123d0a0f6d696e6967616d655f616374696f6e18082001280b" .
            "32242e504f474f50726f746f732e446174612e436f6d6261742e436f6d62" .
            "6174416374696f6e121f0a17717569636b5f737761705f617661696c6162" .
            "6c655f6d7318092001280312250a1d6d696e6967616d655f646566656e73" .
            "655f6368616e6365735f6c656674180a20012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

