<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Combat/CombatPlayerPreferences.proto

namespace GPBMetadata\POGOProtos\Data\Combat;

class CombatPlayerPreferences
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaf010a34504f474f50726f746f732f446174612f436f6d6261742f436f" .
            "6d626174506c61796572507265666572656e6365732e70726f746f121650" .
            "4f474f50726f746f732e446174612e436f6d62617422570a17436f6d6261" .
            "74506c61796572507265666572656e636573121e0a16667269656e64735f" .
            "636f6d6261745f6f70745f6f7574180120012808121c0a146e6561726279" .
            "5f636f6d6261745f6f70745f696e180220012808620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

