<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Avatar/AvatarCustomization.proto

namespace POGOProtos\Data\Avatar\AvatarCustomization;

/**
 * Protobuf type <code>POGOProtos.Data.Avatar.AvatarCustomization.AvatarCustomizationUnlockType</code>
 */
class AvatarCustomizationUnlockType
{
    /**
     * Generated from protobuf enum <code>UNSET_UNLOCK_TYPE = 0;</code>
     */
    const UNSET_UNLOCK_TYPE = 0;
    /**
     * Generated from protobuf enum <code>DEFAULT = 1;</code>
     */
    const PBDEFAULT = 1;
    /**
     * Generated from protobuf enum <code>MEDAL_REWARD = 2;</code>
     */
    const MEDAL_REWARD = 2;
    /**
     * Generated from protobuf enum <code>IAP_CLOTHING = 3;</code>
     */
    const IAP_CLOTHING = 3;
    /**
     * Generated from protobuf enum <code>LEVEL_REWARD = 4;</code>
     */
    const LEVEL_REWARD = 4;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AvatarCustomizationUnlockType::class, \POGOProtos\Data\Avatar\AvatarCustomization_AvatarCustomizationUnlockType::class);

