<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Avatar/AvatarCustomization.proto

namespace POGOProtos\Data\Avatar\AvatarCustomization;

/**
 * Protobuf type <code>POGOProtos.Data.Avatar.AvatarCustomization.AvatarCustomizationPromoType</code>
 */
class AvatarCustomizationPromoType
{
    /**
     * Generated from protobuf enum <code>UNSET_PROMO_TYPE = 0;</code>
     */
    const UNSET_PROMO_TYPE = 0;
    /**
     * Generated from protobuf enum <code>SALE = 1;</code>
     */
    const SALE = 1;
    /**
     * Generated from protobuf enum <code>FEATURED = 2;</code>
     */
    const FEATURED = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(AvatarCustomizationPromoType::class, \POGOProtos\Data\Avatar\AvatarCustomization_AvatarCustomizationPromoType::class);

