<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/TelemetryIds.proto

namespace POGOProtos\Enums;

/**
 * Protobuf type <code>POGOProtos.Enums.AvatarCustomizationTelemetryIds</code>
 */
class AvatarCustomizationTelemetryIds
{
    /**
     * Generated from protobuf enum <code>UNDEFINED_AVATAR_CUSTOMIZATION = 0;</code>
     */
    const UNDEFINED_AVATAR_CUSTOMIZATION = 0;
    /**
     * Generated from protobuf enum <code>EQUIP_ITEM = 1;</code>
     */
    const EQUIP_ITEM = 1;
    /**
     * Generated from protobuf enum <code>OPEN_FEATURES = 2;</code>
     */
    const OPEN_FEATURES = 2;
    /**
     * Generated from protobuf enum <code>OPEN_STORE = 3;</code>
     */
    const OPEN_STORE = 3;
    /**
     * Generated from protobuf enum <code>PURCHASE_ITEM = 4;</code>
     */
    const PURCHASE_ITEM = 4;
    /**
     * Generated from protobuf enum <code>PURCHASE_ERROR = 5;</code>
     */
    const PURCHASE_ERROR = 5;
    /**
     * Generated from protobuf enum <code>SELECT_ITEM_GROUP = 6;</code>
     */
    const SELECT_ITEM_GROUP = 6;
    /**
     * Generated from protobuf enum <code>SELECT_SLOT = 7;</code>
     */
    const SELECT_SLOT = 7;
    /**
     * Generated from protobuf enum <code>SELECT_COLOR = 8;</code>
     */
    const SELECT_COLOR = 8;
    /**
     * Generated from protobuf enum <code>SHOW_QUICK_SHOP = 9;</code>
     */
    const SHOW_QUICK_SHOP = 9;
}

