<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/FriendshipLevelMilestone.proto

namespace POGOProtos\Enums;

/**
 * Protobuf type <code>POGOProtos.Enums.FriendshipLevelMilestone</code>
 */
class FriendshipLevelMilestone
{
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_LEVEL_UNSET = 0;</code>
     */
    const FRIENDSHIP_LEVEL_UNSET = 0;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_LEVEL_0 = 1;</code>
     */
    const FRIENDSHIP_LEVEL_0 = 1;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_LEVEL_1 = 2;</code>
     */
    const FRIENDSHIP_LEVEL_1 = 2;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_LEVEL_2 = 3;</code>
     */
    const FRIENDSHIP_LEVEL_2 = 3;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_LEVEL_3 = 4;</code>
     */
    const FRIENDSHIP_LEVEL_3 = 4;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_LEVEL_4 = 5;</code>
     */
    const FRIENDSHIP_LEVEL_4 = 5;
}

