<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/Gender.proto

namespace POGOProtos\Enums;

/**
 * Protobuf type <code>POGOProtos.Enums.Gender</code>
 */
class Gender
{
    /**
     * Generated from protobuf enum <code>GENDER_UNSET = 0;</code>
     */
    const GENDER_UNSET = 0;
    /**
     * Generated from protobuf enum <code>MALE = 1;</code>
     */
    const MALE = 1;
    /**
     * Generated from protobuf enum <code>FEMALE = 2;</code>
     */
    const FEMALE = 2;
    /**
     * Generated from protobuf enum <code>GENDERLESS = 3;</code>
     */
    const GENDERLESS = 3;
}

