<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/PokemonAnim.proto

namespace POGOProtos\Enums;

/**
 * Protobuf type <code>POGOProtos.Enums.PokemonAnim</code>
 */
class PokemonAnim
{
    /**
     * Generated from protobuf enum <code>NONE_POKEMON_ANIM = 0;</code>
     */
    const NONE_POKEMON_ANIM = 0;
    /**
     * Generated from protobuf enum <code>IDLE_01 = 1;</code>
     */
    const IDLE_01 = 1;
    /**
     * Generated from protobuf enum <code>IDLE_02 = 2;</code>
     */
    const IDLE_02 = 2;
    /**
     * Generated from protobuf enum <code>LAND = 3;</code>
     */
    const LAND = 3;
    /**
     * Generated from protobuf enum <code>ATTACK_01 = 4;</code>
     */
    const ATTACK_01 = 4;
    /**
     * Generated from protobuf enum <code>ATTACK_02 = 5;</code>
     */
    const ATTACK_02 = 5;
    /**
     * Generated from protobuf enum <code>DAMAGED = 6;</code>
     */
    const DAMAGED = 6;
    /**
     * Generated from protobuf enum <code>STUNNED = 7;</code>
     */
    const STUNNED = 7;
    /**
     * Generated from protobuf enum <code>LOOP = 8;</code>
     */
    const LOOP = 8;
    /**
     * Generated from protobuf enum <code>_MAX = 9;</code>
     */
    const _MAX = 9;
}

