<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Telemetry/Distribution.proto

namespace POGOProtos\Networking\Platform\Telemetry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Platform.Telemetry.Distribution.Range</code>
 */
class Distribution_Range extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 min = 1;</code>
     */
    private $min = 0;
    /**
     * <code>int64 max = 2;</code>
     */
    private $max = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Platform\Telemetry\Distribution::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 min = 1;</code>
     */
    public function getMin()
    {
        return $this->min;
    }

    /**
     * <code>int64 min = 1;</code>
     */
    public function setMin($var)
    {
        GPBUtil::checkInt64($var);
        $this->min = $var;
    }

    /**
     * <code>int64 max = 2;</code>
     */
    public function getMax()
    {
        return $this->max;
    }

    /**
     * <code>int64 max = 2;</code>
     */
    public function setMax($var)
    {
        GPBUtil::checkInt64($var);
        $this->max = $var;
    }

}

