<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Telemetry/PlatformMetricData.proto

namespace POGOProtos\Networking\Platform\Telemetry;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Networking\Platform\Telemetry\PlatformMetricData\Kind instead.
     * @deprecated
     */
    class PlatformMetricData_Kind {}
}
class_exists(PlatformMetricData\Kind::class);
@trigger_error('POGOProtos\Networking\Platform\Telemetry\PlatformMetricData_Kind is deprecated and will be removed in the next major release. Use POGOProtos\Networking\Platform\Telemetry\PlatformMetricData\Kind instead', E_USER_DEPRECATED);

