<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Telemetry/PlatformEventData.proto

namespace POGOProtos\Networking\Platform\Telemetry;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Platform.Telemetry.PlatformEventData</code>
 */
class PlatformEventData extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Networking.Platform.Telemetry.TelemetryCommon common_telemetry = 1;</code>
     */
    private $common_telemetry = null;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Platform\Telemetry\PlatformEventData::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Networking.Platform.Telemetry.TelemetryCommon common_telemetry = 1;</code>
     */
    public function getCommonTelemetry()
    {
        return $this->common_telemetry;
    }

    /**
     * <code>.POGOProtos.Networking.Platform.Telemetry.TelemetryCommon common_telemetry = 1;</code>
     */
    public function setCommonTelemetry(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Networking\Platform\Telemetry\TelemetryCommon::class);
        $this->common_telemetry = $var;
    }

}

