<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/BattleResultsExit.proto

namespace GPBMetadata\POGOProtos\Enums;

class BattleResultsExit
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8f010a28504f474f50726f746f732f456e756d732f426174746c655265" .
            "73756c7473457869742e70726f746f1210504f474f50726f746f732e456e" .
            "756d732a490a11426174746c65526573756c747345786974120d0a094c45" .
            "4156455f47594d100012100a0c4c454156455f424154544c45100112130a" .
            "0f434f4e54494e55455f424154544c451002620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

