<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/BuddySize.proto

namespace GPBMetadata\POGOProtos\Enums;

class BuddySize
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa0010a20504f474f50726f746f732f456e756d732f427564647953697a" .
            "652e70726f746f1210504f474f50726f746f732e456e756d732a620a0942" .
            "7564647953697a6512100a0c42554444595f4d454449554d100012120a0e" .
            "42554444595f53484f554c4445521001120d0a0942554444595f42494710" .
            "0212100a0c42554444595f464c59494e471003120e0a0a42554444595f42" .
            "4142591004620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

