<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/CameraZoomInLevel.proto

namespace GPBMetadata\POGOProtos\Enums;

class CameraZoomInLevel
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adf010a28504f474f50726f746f732f456e756d732f43616d6572615a6f" .
            "6f6d496e4c6576656c2e70726f746f1210504f474f50726f746f732e456e" .
            "756d732a98010a1143616d6572615a6f6f6d496e4c6576656c12200a1c44" .
            "454641554c545f43414d4552415f5a4f4f4d5f494e5f4c4556454c100012" .
            "1d0a194e4943455f43414d4552415f5a4f4f4d5f494e5f4c4556454c1001" .
            "121e0a1a47524541545f43414d4552415f5a4f4f4d5f494e5f4c4556454c" .
            "100212220a1e455843454c4c454e545f43414d4552415f5a4f4f4d5f494e" .
            "5f4c4556454c1003620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

