<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/EncounterType.proto

namespace GPBMetadata\POGOProtos\Enums;

class EncounterType
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a88010a24504f474f50726f746f732f456e756d732f456e636f756e7465" .
            "72547970652e70726f746f1210504f474f50726f746f732e456e756d732a" .
            "460a0d456e636f756e74657254797065120f0a0b535041574e5f504f494e" .
            "541000120b0a07494e43454e5345100112080a044449534b1002120d0a09" .
            "504f53545f524149441003620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

