<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Enums/PluginState.proto

namespace GPBMetadata\POGOProtos\Enums;

class PluginState
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab9010a22504f474f50726f746f732f456e756d732f506c7567696e5374" .
            "6174652e70726f746f1210504f474f50726f746f732e456e756d732a790a" .
            "0b506c7567696e537461746512180a14554e4b4e4f574e5f504c5547494e" .
            "5f53544154451000120f0a0b494e495449414c495a45441001120c0a0853" .
            "54415254494e471002120b0a07535441525445441003120b0a0752455355" .
            "4d45441004120a0a065041555345441005120b0a0753544f505045441006" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

