<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/CheckPhotobombMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.CheckPhotobombMessage</code>
 */
class CheckPhotobombMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed64 photo_pokemon_id = 1;</code>
     */
    private $photo_pokemon_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $photo_pokemon_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\CheckPhotobombMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>fixed64 photo_pokemon_id = 1;</code>
     * @return int|string
     */
    public function getPhotoPokemonId()
    {
        return $this->photo_pokemon_id;
    }

    /**
     * Generated from protobuf field <code>fixed64 photo_pokemon_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPhotoPokemonId($var)
    {
        GPBUtil::checkUint64($var);
        $this->photo_pokemon_id = $var;

        return $this;
    }

}

