<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/ClaimCodenameMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.ClaimCodenameMessage</code>
 */
class ClaimCodenameMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string codename = 1;</code>
     */
    private $codename = '';
    /**
     * <code>bool force = 2;</code>
     */
    private $force = false;
    /**
     * <code>bool generate_suggested_codenames = 3;</code>
     */
    private $generate_suggested_codenames = false;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\ClaimCodenameMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>string codename = 1;</code>
     */
    public function getCodename()
    {
        return $this->codename;
    }

    /**
     * <code>string codename = 1;</code>
     */
    public function setCodename($var)
    {
        GPBUtil::checkString($var, True);
        $this->codename = $var;
    }

    /**
     * <code>bool force = 2;</code>
     */
    public function getForce()
    {
        return $this->force;
    }

    /**
     * <code>bool force = 2;</code>
     */
    public function setForce($var)
    {
        GPBUtil::checkBool($var);
        $this->force = $var;
    }

    /**
     * <code>bool generate_suggested_codenames = 3;</code>
     */
    public function getGenerateSuggestedCodenames()
    {
        return $this->generate_suggested_codenames;
    }

    /**
     * <code>bool generate_suggested_codenames = 3;</code>
     */
    public function setGenerateSuggestedCodenames($var)
    {
        GPBUtil::checkBool($var);
        $this->generate_suggested_codenames = $var;
    }

}

