<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/CompleteQuestMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.CompleteQuestMessage</code>
 */
class CompleteQuestMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string quest_id = 1;</code>
     */
    private $quest_id = '';
    /**
     * Generated from protobuf field <code>string sub_quest_id = 2;</code>
     */
    private $sub_quest_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $quest_id
     *     @type string $sub_quest_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\CompleteQuestMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string quest_id = 1;</code>
     * @return string
     */
    public function getQuestId()
    {
        return $this->quest_id;
    }

    /**
     * Generated from protobuf field <code>string quest_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setQuestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->quest_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sub_quest_id = 2;</code>
     * @return string
     */
    public function getSubQuestId()
    {
        return $this->sub_quest_id;
    }

    /**
     * Generated from protobuf field <code>string sub_quest_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubQuestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sub_quest_id = $var;

        return $this;
    }

}

