<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/DiskEncounterMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.DiskEncounterMessage</code>
 */
class DiskEncounterMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint64 encounter_id = 1;</code>
     */
    private $encounter_id = 0;
    /**
     * Generated from protobuf field <code>string fort_id = 2;</code>
     */
    private $fort_id = '';
    /**
     * Generated from protobuf field <code>double player_latitude = 3;</code>
     */
    private $player_latitude = 0.0;
    /**
     * Generated from protobuf field <code>double player_longitude = 4;</code>
     */
    private $player_longitude = 0.0;
    /**
     * Generated from protobuf field <code>double gym_lat_degrees = 5;</code>
     */
    private $gym_lat_degrees = 0.0;
    /**
     * Generated from protobuf field <code>double gym_lng_degrees = 6;</code>
     */
    private $gym_lng_degrees = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $encounter_id
     *     @type string $fort_id
     *     @type float $player_latitude
     *     @type float $player_longitude
     *     @type float $gym_lat_degrees
     *     @type float $gym_lng_degrees
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\DiskEncounterMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 encounter_id = 1;</code>
     * @return int|string
     */
    public function getEncounterId()
    {
        return $this->encounter_id;
    }

    /**
     * Generated from protobuf field <code>uint64 encounter_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEncounterId($var)
    {
        GPBUtil::checkUint64($var);
        $this->encounter_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fort_id = 2;</code>
     * @return string
     */
    public function getFortId()
    {
        return $this->fort_id;
    }

    /**
     * Generated from protobuf field <code>string fort_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFortId($var)
    {
        GPBUtil::checkString($var, True);
        $this->fort_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double player_latitude = 3;</code>
     * @return float
     */
    public function getPlayerLatitude()
    {
        return $this->player_latitude;
    }

    /**
     * Generated from protobuf field <code>double player_latitude = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPlayerLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double player_longitude = 4;</code>
     * @return float
     */
    public function getPlayerLongitude()
    {
        return $this->player_longitude;
    }

    /**
     * Generated from protobuf field <code>double player_longitude = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setPlayerLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_longitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double gym_lat_degrees = 5;</code>
     * @return float
     */
    public function getGymLatDegrees()
    {
        return $this->gym_lat_degrees;
    }

    /**
     * Generated from protobuf field <code>double gym_lat_degrees = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setGymLatDegrees($var)
    {
        GPBUtil::checkDouble($var);
        $this->gym_lat_degrees = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double gym_lng_degrees = 6;</code>
     * @return float
     */
    public function getGymLngDegrees()
    {
        return $this->gym_lng_degrees;
    }

    /**
     * Generated from protobuf field <code>double gym_lng_degrees = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setGymLngDegrees($var)
    {
        GPBUtil::checkDouble($var);
        $this->gym_lng_degrees = $var;

        return $this;
    }

}

