<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/DownloadItemTemplatesMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.DownloadItemTemplatesMessage</code>
 */
class DownloadItemTemplatesMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool paginate = 1;</code>
     */
    private $paginate = false;
    /**
     * Generated from protobuf field <code>int32 page_offset = 2;</code>
     */
    private $page_offset = 0;
    /**
     * Generated from protobuf field <code>uint64 page_timestamp = 3;</code>
     */
    private $page_timestamp = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $paginate
     *     @type int $page_offset
     *     @type int|string $page_timestamp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\DownloadItemTemplatesMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool paginate = 1;</code>
     * @return bool
     */
    public function getPaginate()
    {
        return $this->paginate;
    }

    /**
     * Generated from protobuf field <code>bool paginate = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setPaginate($var)
    {
        GPBUtil::checkBool($var);
        $this->paginate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_offset = 2;</code>
     * @return int
     */
    public function getPageOffset()
    {
        return $this->page_offset;
    }

    /**
     * Generated from protobuf field <code>int32 page_offset = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPageOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_offset = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 page_timestamp = 3;</code>
     * @return int|string
     */
    public function getPageTimestamp()
    {
        return $this->page_timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 page_timestamp = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPageTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->page_timestamp = $var;

        return $this;
    }

}

