<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/DownloadItemTemplatesMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.DownloadItemTemplatesMessage</code>
 */
class DownloadItemTemplatesMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool paginate = 1;</code>
     */
    private $paginate = false;
    /**
     * <code>int32 page_offset = 2;</code>
     */
    private $page_offset = 0;
    /**
     * <code>uint64 page_timestamp = 3;</code>
     */
    private $page_timestamp = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\DownloadItemTemplatesMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool paginate = 1;</code>
     */
    public function getPaginate()
    {
        return $this->paginate;
    }

    /**
     * <code>bool paginate = 1;</code>
     */
    public function setPaginate($var)
    {
        GPBUtil::checkBool($var);
        $this->paginate = $var;
    }

    /**
     * <code>int32 page_offset = 2;</code>
     */
    public function getPageOffset()
    {
        return $this->page_offset;
    }

    /**
     * <code>int32 page_offset = 2;</code>
     */
    public function setPageOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_offset = $var;
    }

    /**
     * <code>uint64 page_timestamp = 3;</code>
     */
    public function getPageTimestamp()
    {
        return $this->page_timestamp;
    }

    /**
     * <code>uint64 page_timestamp = 3;</code>
     */
    public function setPageTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->page_timestamp = $var;
    }

}

