<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/DownloadGmTemplatesMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.DownloadGmTemplatesMessage</code>
 */
class DownloadGmTemplatesMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 basis_batch_id = 1;</code>
     */
    private $basis_batch_id = 0;
    /**
     * Generated from protobuf field <code>int64 batch_id = 2;</code>
     */
    private $batch_id = 0;
    /**
     * Generated from protobuf field <code>int32 page_offset = 3;</code>
     */
    private $page_offset = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $basis_batch_id
     *     @type int|string $batch_id
     *     @type int $page_offset
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\DownloadGmTemplatesMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 basis_batch_id = 1;</code>
     * @return int|string
     */
    public function getBasisBatchId()
    {
        return $this->basis_batch_id;
    }

    /**
     * Generated from protobuf field <code>int64 basis_batch_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBasisBatchId($var)
    {
        GPBUtil::checkInt64($var);
        $this->basis_batch_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 batch_id = 2;</code>
     * @return int|string
     */
    public function getBatchId()
    {
        return $this->batch_id;
    }

    /**
     * Generated from protobuf field <code>int64 batch_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBatchId($var)
    {
        GPBUtil::checkInt64($var);
        $this->batch_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 page_offset = 3;</code>
     * @return int
     */
    public function getPageOffset()
    {
        return $this->page_offset;
    }

    /**
     * Generated from protobuf field <code>int32 page_offset = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setPageOffset($var)
    {
        GPBUtil::checkInt32($var);
        $this->page_offset = $var;

        return $this;
    }

}

