<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetInboxMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.GetInboxMessage</code>
 */
class GetInboxMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool is_history = 1;</code>
     */
    private $is_history = false;
    /**
     * Generated from protobuf field <code>bool is_reverse = 2;</code>
     */
    private $is_reverse = false;
    /**
     * Generated from protobuf field <code>int64 not_before_ms = 3;</code>
     */
    private $not_before_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $is_history
     *     @type bool $is_reverse
     *     @type int|string $not_before_ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\GetInboxMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool is_history = 1;</code>
     * @return bool
     */
    public function getIsHistory()
    {
        return $this->is_history;
    }

    /**
     * Generated from protobuf field <code>bool is_history = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsHistory($var)
    {
        GPBUtil::checkBool($var);
        $this->is_history = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_reverse = 2;</code>
     * @return bool
     */
    public function getIsReverse()
    {
        return $this->is_reverse;
    }

    /**
     * Generated from protobuf field <code>bool is_reverse = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsReverse($var)
    {
        GPBUtil::checkBool($var);
        $this->is_reverse = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 not_before_ms = 3;</code>
     * @return int|string
     */
    public function getNotBeforeMs()
    {
        return $this->not_before_ms;
    }

    /**
     * Generated from protobuf field <code>int64 not_before_ms = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNotBeforeMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->not_before_ms = $var;

        return $this;
    }

}

