<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GymFeedPokemonMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.GymFeedPokemonMessage</code>
 */
class GymFeedPokemonMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Inventory.Item.ItemId item = 1;</code>
     */
    private $item = 0;
    /**
     * Generated from protobuf field <code>int32 starting_quantity = 2;</code>
     */
    private $starting_quantity = 0;
    /**
     * Generated from protobuf field <code>string gym_id = 3;</code>
     */
    private $gym_id = '';
    /**
     * Generated from protobuf field <code>fixed64 pokemon_id = 4;</code>
     */
    private $pokemon_id = 0;
    /**
     * Generated from protobuf field <code>double player_lat_degrees = 5;</code>
     */
    private $player_lat_degrees = 0.0;
    /**
     * Generated from protobuf field <code>double player_lng_degrees = 6;</code>
     */
    private $player_lng_degrees = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $item
     *     @type int $starting_quantity
     *     @type string $gym_id
     *     @type int|string $pokemon_id
     *     @type float $player_lat_degrees
     *     @type float $player_lng_degrees
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\GymFeedPokemonMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Inventory.Item.ItemId item = 1;</code>
     * @return int
     */
    public function getItem()
    {
        return $this->item;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Inventory.Item.ItemId item = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setItem($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Inventory\Item\ItemId::class);
        $this->item = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 starting_quantity = 2;</code>
     * @return int
     */
    public function getStartingQuantity()
    {
        return $this->starting_quantity;
    }

    /**
     * Generated from protobuf field <code>int32 starting_quantity = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStartingQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->starting_quantity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string gym_id = 3;</code>
     * @return string
     */
    public function getGymId()
    {
        return $this->gym_id;
    }

    /**
     * Generated from protobuf field <code>string gym_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGymId($var)
    {
        GPBUtil::checkString($var, True);
        $this->gym_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>fixed64 pokemon_id = 4;</code>
     * @return int|string
     */
    public function getPokemonId()
    {
        return $this->pokemon_id;
    }

    /**
     * Generated from protobuf field <code>fixed64 pokemon_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPokemonId($var)
    {
        GPBUtil::checkUint64($var);
        $this->pokemon_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double player_lat_degrees = 5;</code>
     * @return float
     */
    public function getPlayerLatDegrees()
    {
        return $this->player_lat_degrees;
    }

    /**
     * Generated from protobuf field <code>double player_lat_degrees = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setPlayerLatDegrees($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_lat_degrees = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double player_lng_degrees = 6;</code>
     * @return float
     */
    public function getPlayerLngDegrees()
    {
        return $this->player_lng_degrees;
    }

    /**
     * Generated from protobuf field <code>double player_lng_degrees = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setPlayerLngDegrees($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_lng_degrees = $var;

        return $this;
    }

}

