<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/PlatformClientActionsMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.ProxySocialActionMessage</code>
 */
class ProxySocialActionMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint32 action = 1;</code>
     */
    private $action = 0;
    /**
     * <code>string host = 2;</code>
     */
    private $host = '';
    /**
     * <code>bytes payload = 3;</code>
     */
    private $payload = '';

    public function __construct() {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\PlatformClientActionsMessage::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint32 action = 1;</code>
     */
    public function getAction()
    {
        return $this->action;
    }

    /**
     * <code>uint32 action = 1;</code>
     */
    public function setAction($var)
    {
        GPBUtil::checkUint32($var);
        $this->action = $var;
    }

    /**
     * <code>string host = 2;</code>
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * <code>string host = 2;</code>
     */
    public function setHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->host = $var;
    }

    /**
     * <code>bytes payload = 3;</code>
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * <code>bytes payload = 3;</code>
     */
    public function setPayload($var)
    {
        GPBUtil::checkString($var, False);
        $this->payload = $var;
    }

}

