<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/ReleasePokemonMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.ReleasePokemonMessage</code>
 */
class ReleasePokemonMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>fixed64 pokemon_id = 1;</code>
     */
    private $pokemon_id = 0;
    /**
     * Generated from protobuf field <code>repeated fixed64 pokemon_ids = 2;</code>
     */
    private $pokemon_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $pokemon_id
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $pokemon_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\ReleasePokemonMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>fixed64 pokemon_id = 1;</code>
     * @return int|string
     */
    public function getPokemonId()
    {
        return $this->pokemon_id;
    }

    /**
     * Generated from protobuf field <code>fixed64 pokemon_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setPokemonId($var)
    {
        GPBUtil::checkUint64($var);
        $this->pokemon_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated fixed64 pokemon_ids = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPokemonIds()
    {
        return $this->pokemon_ids;
    }

    /**
     * Generated from protobuf field <code>repeated fixed64 pokemon_ids = 2;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPokemonIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED64);
        $this->pokemon_ids = $arr;

        return $this;
    }

}

