<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/SetAvatarMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.SetAvatarMessage</code>
 */
class SetAvatarMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Player.PlayerAvatar player_avatar = 2;</code>
     */
    private $player_avatar = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \POGOProtos\Data\Player\PlayerAvatar $player_avatar
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\SetAvatarMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Player.PlayerAvatar player_avatar = 2;</code>
     * @return \POGOProtos\Data\Player\PlayerAvatar
     */
    public function getPlayerAvatar()
    {
        return $this->player_avatar;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Player.PlayerAvatar player_avatar = 2;</code>
     * @param \POGOProtos\Data\Player\PlayerAvatar $var
     * @return $this
     */
    public function setPlayerAvatar($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Player\PlayerAvatar::class);
        $this->player_avatar = $var;

        return $this;
    }

}

