<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/StartRaidBattleMessage.proto

namespace POGOProtos\Networking\Requests\Messages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Requests.Messages.StartRaidBattleMessage</code>
 */
class StartRaidBattleMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string gym_id = 1;</code>
     */
    private $gym_id = '';
    /**
     * Generated from protobuf field <code>int64 raid_seed = 2;</code>
     */
    private $raid_seed = 0;
    /**
     * Generated from protobuf field <code>repeated int32 lobby_id = 4;</code>
     */
    private $lobby_id;
    /**
     * Generated from protobuf field <code>repeated fixed64 attacking_pokemon_id = 5;</code>
     */
    private $attacking_pokemon_id;
    /**
     * Generated from protobuf field <code>double player_lat_degrees = 6;</code>
     */
    private $player_lat_degrees = 0.0;
    /**
     * Generated from protobuf field <code>double player_lng_degrees = 7;</code>
     */
    private $player_lng_degrees = 0.0;
    /**
     * Generated from protobuf field <code>double gym_lat_degrees = 8;</code>
     */
    private $gym_lat_degrees = 0.0;
    /**
     * Generated from protobuf field <code>double gym_lng_degrees = 9;</code>
     */
    private $gym_lng_degrees = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $gym_id
     *     @type int|string $raid_seed
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $lobby_id
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $attacking_pokemon_id
     *     @type float $player_lat_degrees
     *     @type float $player_lng_degrees
     *     @type float $gym_lat_degrees
     *     @type float $gym_lng_degrees
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Requests\Messages\StartRaidBattleMessage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string gym_id = 1;</code>
     * @return string
     */
    public function getGymId()
    {
        return $this->gym_id;
    }

    /**
     * Generated from protobuf field <code>string gym_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGymId($var)
    {
        GPBUtil::checkString($var, True);
        $this->gym_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 raid_seed = 2;</code>
     * @return int|string
     */
    public function getRaidSeed()
    {
        return $this->raid_seed;
    }

    /**
     * Generated from protobuf field <code>int64 raid_seed = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRaidSeed($var)
    {
        GPBUtil::checkInt64($var);
        $this->raid_seed = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated int32 lobby_id = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getLobbyId()
    {
        return $this->lobby_id;
    }

    /**
     * Generated from protobuf field <code>repeated int32 lobby_id = 4;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setLobbyId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->lobby_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated fixed64 attacking_pokemon_id = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttackingPokemonId()
    {
        return $this->attacking_pokemon_id;
    }

    /**
     * Generated from protobuf field <code>repeated fixed64 attacking_pokemon_id = 5;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttackingPokemonId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FIXED64);
        $this->attacking_pokemon_id = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double player_lat_degrees = 6;</code>
     * @return float
     */
    public function getPlayerLatDegrees()
    {
        return $this->player_lat_degrees;
    }

    /**
     * Generated from protobuf field <code>double player_lat_degrees = 6;</code>
     * @param float $var
     * @return $this
     */
    public function setPlayerLatDegrees($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_lat_degrees = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double player_lng_degrees = 7;</code>
     * @return float
     */
    public function getPlayerLngDegrees()
    {
        return $this->player_lng_degrees;
    }

    /**
     * Generated from protobuf field <code>double player_lng_degrees = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setPlayerLngDegrees($var)
    {
        GPBUtil::checkDouble($var);
        $this->player_lng_degrees = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double gym_lat_degrees = 8;</code>
     * @return float
     */
    public function getGymLatDegrees()
    {
        return $this->gym_lat_degrees;
    }

    /**
     * Generated from protobuf field <code>double gym_lat_degrees = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setGymLatDegrees($var)
    {
        GPBUtil::checkDouble($var);
        $this->gym_lat_degrees = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double gym_lng_degrees = 9;</code>
     * @return float
     */
    public function getGymLngDegrees()
    {
        return $this->gym_lng_degrees;
    }

    /**
     * Generated from protobuf field <code>double gym_lng_degrees = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setGymLngDegrees($var)
    {
        GPBUtil::checkDouble($var);
        $this->gym_lng_degrees = $var;

        return $this;
    }

}

