<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Responses/ClientTelemetryResponse.proto

namespace POGOProtos\Networking\Platform\Responses\ClientTelemetryResponse;

/**
 * Protobuf type <code>POGOProtos.Networking.Platform.Responses.ClientTelemetryResponse.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>UNSET = 0;</code>
     */
    const PBUNSET = 0;
    /**
     * Generated from protobuf enum <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
    /**
     * Generated from protobuf enum <code>FAILURE = 2;</code>
     */
    const FAILURE = 2;
    /**
     * Generated from protobuf enum <code>ERROR_INVALID_REQUEST = 3;</code>
     */
    const ERROR_INVALID_REQUEST = 3;
    /**
     * Generated from protobuf enum <code>ERROR_INVALID_PROTO = 4;</code>
     */
    const ERROR_INVALID_PROTO = 4;
    /**
     * Generated from protobuf enum <code>ERROR_UNSET_TELEMETRY_ID = 5;</code>
     */
    const ERROR_UNSET_TELEMETRY_ID = 5;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \POGOProtos\Networking\Platform\Responses\ClientTelemetryResponse_Status::class);

