<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Friends/FriendshipData.proto

namespace POGOProtos\Data\Friends;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Friends.FriendshipData</code>
 */
class FriendshipData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Friends.FriendshipLevelData friendship_level_data = 1;</code>
     */
    private $friendship_level_data = null;
    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Gift.GiftBoxDetails giftbox_details = 2;</code>
     */
    private $giftbox_details;
    /**
     * Generated from protobuf field <code>string codename = 3;</code>
     */
    private $codename = '';
    /**
     * Generated from protobuf field <code>string nickname = 4;</code>
     */
    private $nickname = '';
    /**
     * Generated from protobuf field <code>int64 open_trade_expire_ms = 5;</code>
     */
    private $open_trade_expire_ms = 0;
    /**
     * Generated from protobuf field <code>bool is_lucky = 6;</code>
     */
    private $is_lucky = false;
    /**
     * Generated from protobuf field <code>int32 lucky_count = 7;</code>
     */
    private $lucky_count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \POGOProtos\Data\Friends\FriendshipLevelData $friendship_level_data
     *     @type \POGOProtos\Data\Gift\GiftBoxDetails[]|\Google\Protobuf\Internal\RepeatedField $giftbox_details
     *     @type string $codename
     *     @type string $nickname
     *     @type int|string $open_trade_expire_ms
     *     @type bool $is_lucky
     *     @type int $lucky_count
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Friends\FriendshipData::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Friends.FriendshipLevelData friendship_level_data = 1;</code>
     * @return \POGOProtos\Data\Friends\FriendshipLevelData
     */
    public function getFriendshipLevelData()
    {
        return $this->friendship_level_data;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Friends.FriendshipLevelData friendship_level_data = 1;</code>
     * @param \POGOProtos\Data\Friends\FriendshipLevelData $var
     * @return $this
     */
    public function setFriendshipLevelData($var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\Friends\FriendshipLevelData::class);
        $this->friendship_level_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Gift.GiftBoxDetails giftbox_details = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGiftboxDetails()
    {
        return $this->giftbox_details;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Gift.GiftBoxDetails giftbox_details = 2;</code>
     * @param \POGOProtos\Data\Gift\GiftBoxDetails[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGiftboxDetails($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\Gift\GiftBoxDetails::class);
        $this->giftbox_details = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string codename = 3;</code>
     * @return string
     */
    public function getCodename()
    {
        return $this->codename;
    }

    /**
     * Generated from protobuf field <code>string codename = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCodename($var)
    {
        GPBUtil::checkString($var, True);
        $this->codename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nickname = 4;</code>
     * @return string
     */
    public function getNickname()
    {
        return $this->nickname;
    }

    /**
     * Generated from protobuf field <code>string nickname = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 open_trade_expire_ms = 5;</code>
     * @return int|string
     */
    public function getOpenTradeExpireMs()
    {
        return $this->open_trade_expire_ms;
    }

    /**
     * Generated from protobuf field <code>int64 open_trade_expire_ms = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOpenTradeExpireMs($var)
    {
        GPBUtil::checkInt64($var);
        $this->open_trade_expire_ms = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_lucky = 6;</code>
     * @return bool
     */
    public function getIsLucky()
    {
        return $this->is_lucky;
    }

    /**
     * Generated from protobuf field <code>bool is_lucky = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsLucky($var)
    {
        GPBUtil::checkBool($var);
        $this->is_lucky = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 lucky_count = 7;</code>
     * @return int
     */
    public function getLuckyCount()
    {
        return $this->lucky_count;
    }

    /**
     * Generated from protobuf field <code>int32 lucky_count = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLuckyCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->lucky_count = $var;

        return $this;
    }

}

