<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Friends/PlayerFriendDisplay.proto

namespace POGOProtos\Data\Friends;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Data.Friends.PlayerFriendDisplay</code>
 */
class PlayerFriendDisplay extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.POGOProtos.Data.PokemonDisplay buddy = 1;</code>
     */
    private $buddy = null;
    /**
     * <code>int32 buddy_display_pokemon_id = 2;</code>
     */
    private $buddy_display_pokemon_id = 0;
    /**
     * <code>string buddy_pokemon_nickname = 3;</code>
     */
    private $buddy_pokemon_nickname = '';
    /**
     * <code>.POGOProtos.Data.PokemonDisplay last_pokemon_caught = 4;</code>
     */
    private $last_pokemon_caught = null;
    /**
     * <code>int32 last_pokemon_caught_display_id = 5;</code>
     */
    private $last_pokemon_caught_display_id = 0;
    /**
     * <code>int64 last_pokemon_caught_timestamp = 6;</code>
     */
    private $last_pokemon_caught_timestamp = 0;

    public function __construct() {
        \GPBMetadata\POGOProtos\Data\Friends\PlayerFriendDisplay::initOnce();
        parent::__construct();
    }

    /**
     * <code>.POGOProtos.Data.PokemonDisplay buddy = 1;</code>
     */
    public function getBuddy()
    {
        return $this->buddy;
    }

    /**
     * <code>.POGOProtos.Data.PokemonDisplay buddy = 1;</code>
     */
    public function setBuddy(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\PokemonDisplay::class);
        $this->buddy = $var;
    }

    /**
     * <code>int32 buddy_display_pokemon_id = 2;</code>
     */
    public function getBuddyDisplayPokemonId()
    {
        return $this->buddy_display_pokemon_id;
    }

    /**
     * <code>int32 buddy_display_pokemon_id = 2;</code>
     */
    public function setBuddyDisplayPokemonId($var)
    {
        GPBUtil::checkInt32($var);
        $this->buddy_display_pokemon_id = $var;
    }

    /**
     * <code>string buddy_pokemon_nickname = 3;</code>
     */
    public function getBuddyPokemonNickname()
    {
        return $this->buddy_pokemon_nickname;
    }

    /**
     * <code>string buddy_pokemon_nickname = 3;</code>
     */
    public function setBuddyPokemonNickname($var)
    {
        GPBUtil::checkString($var, True);
        $this->buddy_pokemon_nickname = $var;
    }

    /**
     * <code>.POGOProtos.Data.PokemonDisplay last_pokemon_caught = 4;</code>
     */
    public function getLastPokemonCaught()
    {
        return $this->last_pokemon_caught;
    }

    /**
     * <code>.POGOProtos.Data.PokemonDisplay last_pokemon_caught = 4;</code>
     */
    public function setLastPokemonCaught(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Data\PokemonDisplay::class);
        $this->last_pokemon_caught = $var;
    }

    /**
     * <code>int32 last_pokemon_caught_display_id = 5;</code>
     */
    public function getLastPokemonCaughtDisplayId()
    {
        return $this->last_pokemon_caught_display_id;
    }

    /**
     * <code>int32 last_pokemon_caught_display_id = 5;</code>
     */
    public function setLastPokemonCaughtDisplayId($var)
    {
        GPBUtil::checkInt32($var);
        $this->last_pokemon_caught_display_id = $var;
    }

    /**
     * <code>int64 last_pokemon_caught_timestamp = 6;</code>
     */
    public function getLastPokemonCaughtTimestamp()
    {
        return $this->last_pokemon_caught_timestamp;
    }

    /**
     * <code>int64 last_pokemon_caught_timestamp = 6;</code>
     */
    public function setLastPokemonCaughtTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_pokemon_caught_timestamp = $var;
    }

}

