<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Avatar/AvatarCustomization.proto

namespace POGOProtos\Data\Avatar;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Data\Avatar\AvatarCustomization\AvatarCustomizationUnlockType instead.
     * @deprecated
     */
    class AvatarCustomization_AvatarCustomizationUnlockType {}
}
class_exists(AvatarCustomization\AvatarCustomizationUnlockType::class);
@trigger_error('POGOProtos\Data\Avatar\AvatarCustomization_AvatarCustomizationUnlockType is deprecated and will be removed in the next major release. Use POGOProtos\Data\Avatar\AvatarCustomization\AvatarCustomizationUnlockType instead', E_USER_DEPRECATED);

