<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Raid/Lobby.proto

namespace GPBMetadata\POGOProtos\Data\Raid;

class Lobby
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Battle\BattleParticipant::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab4030a20504f474f50726f746f732f446174612f526169642f4c6f6262" .
            "792e70726f746f1214504f474f50726f746f732e446174612e526169641a" .
            "2e504f474f50726f746f732f446174612f426174746c652f426174746c65" .
            "5061727469636970616e742e70726f746f22c1020a054c6f62627912100a" .
            "086c6f6262795f6964180120032805123a0a07706c617965727318022003" .
            "280b32292e504f474f50726f746f732e446174612e426174746c652e4261" .
            "74746c655061727469636970616e74121a0a12706c617965725f6a6f696e" .
            "5f656e645f6d7318032001280312200a18706f6b656d6f6e5f73656c6563" .
            "74696f6e5f656e645f6d73180420012803121c0a14726169645f62617474" .
            "6c655f73746172745f6d73180520012803121a0a12726169645f62617474" .
            "6c655f656e645f6d7318062001280312160a0e726169645f626174746c65" .
            "5f696418082001280912160a0e6f776e65725f6e69636b6e616d65180920" .
            "012809120f0a0770726976617465180a2001280812130a0b637265617469" .
            "6f6e5f6d73180b20012803121c0a14626174746c655f706c66655f696e73" .
            "74616e6365180c20012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

