<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Raid/Lobby.proto

namespace GPBMetadata\POGOProtos\Data\Raid;

class Lobby
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Battle\BattleParticipant::initOnce();
        \GPBMetadata\POGOProtos\Data\PokemonDisplay::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa7040a20504f474f50726f746f732f446174612f526169642f4c6f6262" .
            "792e70726f746f1214504f474f50726f746f732e446174612e526169641a" .
            "2e504f474f50726f746f732f446174612f426174746c652f426174746c65" .
            "5061727469636970616e742e70726f746f1a24504f474f50726f746f732f" .
            "446174612f506f6b656d6f6e446973706c61792e70726f746f228e030a05" .
            "4c6f62627912100a086c6f6262795f6964180120032805123a0a07706c61" .
            "7965727318022003280b32292e504f474f50726f746f732e446174612e42" .
            "6174746c652e426174746c655061727469636970616e74121a0a12706c61" .
            "7965725f6a6f696e5f656e645f6d7318032001280312200a18706f6b656d" .
            "6f6e5f73656c656374696f6e5f656e645f6d73180420012803121c0a1472" .
            "6169645f626174746c655f73746172745f6d73180520012803121a0a1272" .
            "6169645f626174746c655f656e645f6d7318062001280312160a0e726169" .
            "645f626174746c655f696418082001280912160a0e6f776e65725f6e6963" .
            "6b6e616d65180920012809120f0a0770726976617465180a200128081213" .
            "0a0b6372656174696f6e5f6d73180b20012803121c0a14626174746c655f" .
            "706c66655f696e7374616e6365180c20012805124b0a1177656174686572" .
            "5f636f6e646974696f6e180d2001280e32302e504f474f50726f746f732e" .
            "446174612e506f6b656d6f6e446973706c61792e57656174686572436f6e" .
            "646974696f6e620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

