<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Raid/RaidInfo.proto

namespace GPBMetadata\POGOProtos\Data\Raid;

class RaidInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\PokemonData::initOnce();
        \GPBMetadata\POGOProtos\Enums\RaidLevel::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaf030a23504f474f50726f746f732f446174612f526169642f52616964" .
            "496e666f2e70726f746f1214504f474f50726f746f732e446174612e5261" .
            "69641a20504f474f50726f746f732f456e756d732f526169644c6576656c" .
            "2e70726f746f22c7020a0852616964496e666f12110a09726169645f7365" .
            "656418012001280312150a0d726169645f737061776e5f6d731802200128" .
            "0312160a0e726169645f626174746c655f6d7318032001280312130a0b72" .
            "6169645f656e645f6d7318042001280312320a0c726169645f706f6b656d" .
            "6f6e18052001280b321c2e504f474f50726f746f732e446174612e506f6b" .
            "656d6f6e44617461122f0a0a726169645f6c6576656c18062001280e321b" .
            "2e504f474f50726f746f732e456e756d732e526169644c6576656c12100a" .
            "08636f6d706c65746518072001280812140a0c69735f6578636c75736976" .
            "6518082001280812160a0e69735f726169645f68696464656e1809200128" .
            "0812190a1169735f7363686564756c65645f72616964180a20012808120f" .
            "0a0769735f66726565180b2001280812130a0b63616d706169676e5f6964" .
            "180c20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

