<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Raid/RaidEncounter.proto

namespace GPBMetadata\POGOProtos\Data\Raid;

class RaidEncounter
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\PokemonData::initOnce();
        \GPBMetadata\POGOProtos\Data\Capture\CaptureProbability::initOnce();
        \GPBMetadata\POGOProtos\Enums\RaidLevel::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad5030a28504f474f50726f746f732f446174612f526169642f52616964" .
            "456e636f756e7465722e70726f746f1214504f474f50726f746f732e4461" .
            "74612e526169641a21504f474f50726f746f732f446174612f506f6b656d" .
            "6f6e446174612e70726f746f1a30504f474f50726f746f732f446174612f" .
            "436170747572652f4361707475726550726f626162696c6974792e70726f" .
            "746f1a20504f474f50726f746f732f456e756d732f526169644c6576656c" .
            "2e70726f746f2293020a0d52616964456e636f756e746572122d0a07706f" .
            "6b656d6f6e18012001280b321c2e504f474f50726f746f732e446174612e" .
            "506f6b656d6f6e4461746112140a0c656e636f756e7465725f6964180220" .
            "01280312150a0d737061776e706f696e745f6964180320012809124a0a15" .
            "636170747572655f70726f626162696c697469657318042001280b322b2e" .
            "504f474f50726f746f732e446174612e436170747572652e436170747572" .
            "6550726f626162696c69747912180a107468726f77735f72656d61696e69" .
            "6e67180520012805122f0a0a726169645f6c6576656c18062001280e321b" .
            "2e504f474f50726f746f732e456e756d732e526169644c6576656c120f0a" .
            "07666f72745f6964180720012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

