<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Requests/UnknownPtr8Request.proto

namespace GPBMetadata\POGOProtos\Networking\Platform\Requests;

class UnknownPtr8Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9a010a40504f474f50726f746f732f4e6574776f726b696e672f506c61" .
            "74666f726d2f52657175657374732f556e6b6e6f776e5074723852657175" .
            "6573742e70726f746f1227504f474f50726f746f732e4e6574776f726b69" .
            "6e672e506c6174666f726d2e526571756573747322250a12556e6b6e6f77" .
            "6e5074723852657175657374120f0a076d65737361676518012001280962" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

