<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Fitness/FitnessMetricsReportHistory.proto

namespace POGOProtos\Data\Fitness;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Data\Fitness\FitnessMetricsReportHistory\MetricsHistory instead.
     * @deprecated
     */
    class FitnessMetricsReportHistory_MetricsHistory {}
}
class_exists(FitnessMetricsReportHistory\MetricsHistory::class);
@trigger_error('POGOProtos\Data\Fitness\FitnessMetricsReportHistory_MetricsHistory is deprecated and will be removed in the next major release. Use POGOProtos\Data\Fitness\FitnessMetricsReportHistory\MetricsHistory instead', E_USER_DEPRECATED);

