<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Store/CurrencyUpdate.proto

namespace POGOProtos\Data\Store;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Store.CurrencyUpdate</code>
 */
class CurrencyUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string currency_name = 1;</code>
     */
    private $currency_name = '';
    /**
     * Generated from protobuf field <code>int32 currency_delta = 2;</code>
     */
    private $currency_delta = 0;
    /**
     * Generated from protobuf field <code>int32 currency_balance = 3;</code>
     */
    private $currency_balance = 0;
    /**
     * Generated from protobuf field <code>int32 fiat_purchased_balance = 4;</code>
     */
    private $fiat_purchased_balance = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $currency_name
     *     @type int $currency_delta
     *     @type int $currency_balance
     *     @type int $fiat_purchased_balance
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Store\CurrencyUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string currency_name = 1;</code>
     * @return string
     */
    public function getCurrencyName()
    {
        return $this->currency_name;
    }

    /**
     * Generated from protobuf field <code>string currency_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyName($var)
    {
        GPBUtil::checkString($var, True);
        $this->currency_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 currency_delta = 2;</code>
     * @return int
     */
    public function getCurrencyDelta()
    {
        return $this->currency_delta;
    }

    /**
     * Generated from protobuf field <code>int32 currency_delta = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrencyDelta($var)
    {
        GPBUtil::checkInt32($var);
        $this->currency_delta = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 currency_balance = 3;</code>
     * @return int
     */
    public function getCurrencyBalance()
    {
        return $this->currency_balance;
    }

    /**
     * Generated from protobuf field <code>int32 currency_balance = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrencyBalance($var)
    {
        GPBUtil::checkInt32($var);
        $this->currency_balance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 fiat_purchased_balance = 4;</code>
     * @return int
     */
    public function getFiatPurchasedBalance()
    {
        return $this->fiat_purchased_balance;
    }

    /**
     * Generated from protobuf field <code>int32 fiat_purchased_balance = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setFiatPurchasedBalance($var)
    {
        GPBUtil::checkInt32($var);
        $this->fiat_purchased_balance = $var;

        return $this;
    }

}

