<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/AssetCache/JournalAddEntry.proto

namespace GPBMetadata\POGOProtos\Data\AssetCache;

class JournalAddEntry
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\AssetCache\HashedKey::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae4010a30504f474f50726f746f732f446174612f417373657443616368" .
            "652f4a6f75726e616c416464456e7472792e70726f746f121a504f474f50" .
            "726f746f732e446174612e417373657443616368651a2a504f474f50726f" .
            "746f732f446174612f417373657443616368652f4861736865644b65792e" .
            "70726f746f22600a0f4a6f75726e616c416464456e74727912390a0a6861" .
            "736865645f6b657918012001280b32252e504f474f50726f746f732e4461" .
            "74612e417373657443616368652e4861736865644b657912120a0a656e74" .
            "72795f73697a65180220012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

