<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Platform/Ditto/LocationUpdateEventParams.proto

namespace POGOProtos\Networking\Platform\Ditto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Networking.Platform.Ditto.LocationUpdateEventParams</code>
 */
class LocationUpdateEventParams extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>double latitude_deg = 1;</code>
     */
    private $latitude_deg = 0.0;
    /**
     * Generated from protobuf field <code>double longitude_deg = 2;</code>
     */
    private $longitude_deg = 0.0;
    /**
     * Generated from protobuf field <code>double altitude_m = 3;</code>
     */
    private $altitude_m = 0.0;
    /**
     * Generated from protobuf field <code>double accuracy_m = 4;</code>
     */
    private $accuracy_m = 0.0;
    /**
     * Generated from protobuf field <code>double timestamp_s = 5;</code>
     */
    private $timestamp_s = 0.0;
    /**
     * Generated from protobuf field <code>uint32 provider_status = 6;</code>
     */
    private $provider_status = 0;
    /**
     * Generated from protobuf field <code>uint32 location_type = 7;</code>
     */
    private $location_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $latitude_deg
     *     @type float $longitude_deg
     *     @type float $altitude_m
     *     @type float $accuracy_m
     *     @type float $timestamp_s
     *     @type int $provider_status
     *     @type int $location_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Networking\Platform\Ditto\LocationUpdateEventParams::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>double latitude_deg = 1;</code>
     * @return float
     */
    public function getLatitudeDeg()
    {
        return $this->latitude_deg;
    }

    /**
     * Generated from protobuf field <code>double latitude_deg = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitudeDeg($var)
    {
        GPBUtil::checkDouble($var);
        $this->latitude_deg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double longitude_deg = 2;</code>
     * @return float
     */
    public function getLongitudeDeg()
    {
        return $this->longitude_deg;
    }

    /**
     * Generated from protobuf field <code>double longitude_deg = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitudeDeg($var)
    {
        GPBUtil::checkDouble($var);
        $this->longitude_deg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double altitude_m = 3;</code>
     * @return float
     */
    public function getAltitudeM()
    {
        return $this->altitude_m;
    }

    /**
     * Generated from protobuf field <code>double altitude_m = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setAltitudeM($var)
    {
        GPBUtil::checkDouble($var);
        $this->altitude_m = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double accuracy_m = 4;</code>
     * @return float
     */
    public function getAccuracyM()
    {
        return $this->accuracy_m;
    }

    /**
     * Generated from protobuf field <code>double accuracy_m = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setAccuracyM($var)
    {
        GPBUtil::checkDouble($var);
        $this->accuracy_m = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double timestamp_s = 5;</code>
     * @return float
     */
    public function getTimestampS()
    {
        return $this->timestamp_s;
    }

    /**
     * Generated from protobuf field <code>double timestamp_s = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setTimestampS($var)
    {
        GPBUtil::checkDouble($var);
        $this->timestamp_s = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 provider_status = 6;</code>
     * @return int
     */
    public function getProviderStatus()
    {
        return $this->provider_status;
    }

    /**
     * Generated from protobuf field <code>uint32 provider_status = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setProviderStatus($var)
    {
        GPBUtil::checkUint32($var);
        $this->provider_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 location_type = 7;</code>
     * @return int
     */
    public function getLocationType()
    {
        return $this->location_type;
    }

    /**
     * Generated from protobuf field <code>uint32 location_type = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLocationType($var)
    {
        GPBUtil::checkUint32($var);
        $this->location_type = $var;

        return $this;
    }

}

