<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/News/NewsArticle.proto

namespace POGOProtos\Data\News;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Data\News\NewsArticle\NewsTemplate instead.
     * @deprecated
     */
    class NewsArticle_NewsTemplate {}
}
class_exists(NewsArticle\NewsTemplate::class);
@trigger_error('POGOProtos\Data\News\NewsArticle_NewsTemplate is deprecated and will be removed in the next major release. Use POGOProtos\Data\News\NewsArticle\NewsTemplate instead', E_USER_DEPRECATED);

