<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/CheckPhotobombResponse.proto

namespace POGOProtos\Networking\Responses\CheckPhotobombResponse;

/**
 * Protobuf type <code>POGOProtos.Networking.Responses.CheckPhotobombResponse.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>UNSET = 0;</code>
     */
    const PBUNSET = 0;
    /**
     * Generated from protobuf enum <code>SUCCESS = 1;</code>
     */
    const SUCCESS = 1;
    /**
     * Generated from protobuf enum <code>ERROR_PHOTO_POKEMON_INVALID = 2;</code>
     */
    const ERROR_PHOTO_POKEMON_INVALID = 2;
    /**
     * Generated from protobuf enum <code>ERROR_UNKNOWN = 3;</code>
     */
    const ERROR_UNKNOWN = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Status::class, \POGOProtos\Networking\Responses\CheckPhotobombResponse_Status::class);

