<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Beluga/BelugaIncenseBox.proto

namespace GPBMetadata\POGOProtos\Data\Beluga;

class BelugaIncenseBox
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9f010a2d504f474f50726f746f732f446174612f42656c7567612f4265" .
            "6c756761496e63656e7365426f782e70726f746f1216504f474f50726f74" .
            "6f732e446174612e42656c756761224e0a1042656c756761496e63656e73" .
            "65426f7812110a0969735f757361626c6518012001280812270a1f636f6f" .
            "6c5f646f776e5f66696e69736865645f74696d657374616d705f6d731802" .
            "20012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

