<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/Social/GetFriendshipMilestoneRewardsResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses\Social;

class GetFriendshipMilestoneRewardsResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac8030a52504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f536f6369616c2f476574467269656e64736869704d696c" .
            "6573746f6e6552657761726473526573706f6e73652e70726f746f122650" .
            "4f474f50726f746f732e4e6574776f726b696e672e526573706f6e736573" .
            "2e536f6369616c22c1020a25476574467269656e64736869704d696c6573" .
            "746f6e6552657761726473526573706f6e736512640a06726573756c7418" .
            "012001280e32542e504f474f50726f746f732e4e6574776f726b696e672e" .
            "526573706f6e7365732e536f6369616c2e476574467269656e6473686970" .
            "4d696c6573746f6e6552657761726473526573706f6e73652e526573756c" .
            "7412110a0978705f72657761726418022001280312110a09667269656e64" .
            "5f6964180320012809228b010a06526573756c7412090a05554e53455410" .
            "00120b0a0753554343455353100112110a0d4552524f525f554e4b4e4f57" .
            "4e100212150a114552524f525f4e4f545f465249454e4453100312230a1f" .
            "4552524f525f4d494c4553544f4e455f414c52454144595f415741524445" .
            "441004121a0a164552524f525f4641494c45445f544f5f55504441544510" .
            "05620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

