<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/Social/GetInboxResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses\Social;

class GetInboxResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Inbox\ClientInbox::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab7020a3d504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f536f6369616c2f476574496e626f78526573706f6e7365" .
            "2e70726f746f1226504f474f50726f746f732e4e6574776f726b696e672e" .
            "526573706f6e7365732e536f6369616c22c5010a10476574496e626f7852" .
            "6573706f6e7365124f0a06726573756c7418012001280e323f2e504f474f" .
            "50726f746f732e4e6574776f726b696e672e526573706f6e7365732e536f" .
            "6369616c2e476574496e626f78526573706f6e73652e526573756c741231" .
            "0a05696e626f7818022001280b32222e504f474f50726f746f732e446174" .
            "612e496e626f782e436c69656e74496e626f78222d0a06526573756c7412" .
            "090a05554e5345541000120b0a07535543434553531001120b0a07464149" .
            "4c5552451002620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

