<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/Social/GetIncomingFriendInvitesResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses\Social;

class GetIncomingFriendInvitesResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Data\Friends\IncomingFriendInviteDisplay::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a81030a4d504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f536f6369616c2f476574496e636f6d696e67467269656e" .
            "64496e7669746573526573706f6e73652e70726f746f1226504f474f5072" .
            "6f746f732e4e6574776f726b696e672e526573706f6e7365732e536f6369" .
            "616c22ff010a20476574496e636f6d696e67467269656e64496e76697465" .
            "73526573706f6e7365125f0a06726573756c7418012001280e324f2e504f" .
            "474f50726f746f732e4e6574776f726b696e672e526573706f6e7365732e" .
            "536f6369616c2e476574496e636f6d696e67467269656e64496e76697465" .
            "73526573706f6e73652e526573756c7412450a07696e7669746573180220" .
            "03280b32342e504f474f50726f746f732e446174612e467269656e64732e" .
            "496e636f6d696e67467269656e64496e76697465446973706c617922330a" .
            "06526573756c7412090a05554e5345541000120b0a075355434345535310" .
            "0112110a0d4552524f525f554e4b4e4f574e1002620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

