<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/Social/RemoveFriendResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses\Social;

class RemoveFriendResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acb020a41504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f536f6369616c2f52656d6f7665467269656e6452657370" .
            "6f6e73652e70726f746f1226504f474f50726f746f732e4e6574776f726b" .
            "696e672e526573706f6e7365732e536f6369616c22d5010a1452656d6f76" .
            "65467269656e64526573706f6e736512530a06726573756c741801200128" .
            "0e32432e504f474f50726f746f732e4e6574776f726b696e672e52657370" .
            "6f6e7365732e536f6369616c2e52656d6f7665467269656e64526573706f" .
            "6e73652e526573756c7422680a06526573756c7412090a05554e53455410" .
            "00120b0a0753554343455353100112270a234552524f525f504c41594552" .
            "5f444f45535f4e4f545f45584953545f44454c455445441002121d0a1945" .
            "52524f525f504c415945525f4e4f545f415f465249454e44100362067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

