<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Responses/Social/UpdateFacebookStatusResponse.proto

namespace GPBMetadata\POGOProtos\Networking\Responses\Social;

class UpdateFacebookStatusResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0afd020a49504f474f50726f746f732f4e6574776f726b696e672f526573" .
            "706f6e7365732f536f6369616c2f55706461746546616365626f6f6b5374" .
            "61747573526573706f6e73652e70726f746f1226504f474f50726f746f73" .
            "2e4e6574776f726b696e672e526573706f6e7365732e536f6369616c22ff" .
            "010a1c55706461746546616365626f6f6b537461747573526573706f6e73" .
            "65125b0a06726573756c7418012001280e324b2e504f474f50726f746f73" .
            "2e4e6574776f726b696e672e526573706f6e7365732e536f6369616c2e55" .
            "706461746546616365626f6f6b537461747573526573706f6e73652e5265" .
            "73756c742281010a06526573756c7412090a05554e5345541000120b0a07" .
            "53554343455353100112110a0d4552524f525f554e4b4e4f574e1002121a" .
            "0a164552524f525f504c415945525f4e4f545f464f554e44100312160a12" .
            "4552524f525f46414345424f4f4b5f415049100412180a144552524f525f" .
            "414c52454144595f4558495354531005620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

