<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Pokemon/LobbyPokemon.proto

namespace GPBMetadata\POGOProtos\Map\Pokemon;

class LobbyPokemon
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\PokemonId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ade010a29504f474f50726f746f732f4d61702f506f6b656d6f6e2f4c6f" .
            "626279506f6b656d6f6e2e70726f746f1216504f474f50726f746f732e4d" .
            "61702e506f6b656d6f6e1a20504f474f50726f746f732f456e756d732f50" .
            "6f6b656d6f6e49642e70726f746f226f0a0c4c6f626279506f6b656d6f6e" .
            "120a0a026964180120012803122f0a0a706f6b656465785f696418022001" .
            "280e321b2e504f474f50726f746f732e456e756d732e506f6b656d6f6e49" .
            "64120a0a02637018032001280512160a0e70657263656e745f6865616c74" .
            "68180420012802620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

