<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Pokemon/NearbyPokemon.proto

namespace GPBMetadata\POGOProtos\Map\Pokemon;

class NearbyPokemon
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\PokemonId::initOnce();
        \GPBMetadata\POGOProtos\Data\PokemonDisplay::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aca020a2a504f474f50726f746f732f4d61702f506f6b656d6f6e2f4e65" .
            "61726279506f6b656d6f6e2e70726f746f1216504f474f50726f746f732e" .
            "4d61702e506f6b656d6f6e1a24504f474f50726f746f732f446174612f50" .
            "6f6b656d6f6e446973706c61792e70726f746f22d5010a0d4e6561726279" .
            "506f6b656d6f6e122f0a0a706f6b656d6f6e5f696418012001280e321b2e" .
            "504f474f50726f746f732e456e756d732e506f6b656d6f6e4964121a0a12" .
            "64697374616e63655f696e5f6d657465727318022001280212140a0c656e" .
            "636f756e7465725f6964180320012806120f0a07666f72745f6964180420" .
            "01280912160a0e666f72745f696d6167655f75726c18052001280912380a" .
            "0f706f6b656d6f6e5f646973706c617918062001280b321f2e504f474f50" .
            "726f746f732e446174612e506f6b656d6f6e446973706c6179620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

