<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/QuestCondition.proto

namespace POGOProtos\Data\Quests\QuestCondition;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Quests.QuestCondition.WithPvpCombat</code>
 */
class WithPvpCombat extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool requires_win = 1;</code>
     */
    private $requires_win = false;
    /**
     * Generated from protobuf field <code>repeated string combat_league_template_id = 2;</code>
     */
    private $combat_league_template_id;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $requires_win
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $combat_league_template_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Quests\QuestCondition::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool requires_win = 1;</code>
     * @return bool
     */
    public function getRequiresWin()
    {
        return $this->requires_win;
    }

    /**
     * Generated from protobuf field <code>bool requires_win = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequiresWin($var)
    {
        GPBUtil::checkBool($var);
        $this->requires_win = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string combat_league_template_id = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCombatLeagueTemplateId()
    {
        return $this->combat_league_template_id;
    }

    /**
     * Generated from protobuf field <code>repeated string combat_league_template_id = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCombatLeagueTemplateId($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->combat_league_template_id = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(WithPvpCombat::class, \POGOProtos\Data\Quests\QuestCondition_WithPvpCombat::class);

