<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/QuestCondition.proto

namespace POGOProtos\Data\Quests\QuestCondition;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Quests.QuestCondition.WithRaidLevel</code>
 */
class WithRaidLevel extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Raid.RaidInfo.RaidLevel raid_level = 1;</code>
     */
    private $raid_level;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $raid_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Quests\QuestCondition::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Raid.RaidInfo.RaidLevel raid_level = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRaidLevel()
    {
        return $this->raid_level;
    }

    /**
     * Generated from protobuf field <code>repeated .POGOProtos.Data.Raid.RaidInfo.RaidLevel raid_level = 1;</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRaidLevel($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \POGOProtos\Data\Raid\RaidInfo\RaidLevel::class);
        $this->raid_level = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(WithRaidLevel::class, \POGOProtos\Data\Quests\QuestCondition_WithRaidLevel::class);

