<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Weather/ClientWeather.proto

namespace POGOProtos\Map\Weather;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Map.Weather.ClientWeather</code>
 */
class ClientWeather extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 s2_cell_id = 1;</code>
     */
    private $s2_cell_id = 0;
    /**
     * <code>.POGOProtos.Map.Weather.DisplayWeather display_weather = 2;</code>
     */
    private $display_weather = null;
    /**
     * <code>.POGOProtos.Map.Weather.GameplayWeather gameplay_weather = 3;</code>
     */
    private $gameplay_weather = null;
    /**
     * <code>repeated .POGOProtos.Map.Weather.WeatherAlert alerts = 4;</code>
     */
    private $alerts;

    public function __construct() {
        \GPBMetadata\POGOProtos\Map\Weather\ClientWeather::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 s2_cell_id = 1;</code>
     */
    public function getS2CellId()
    {
        return $this->s2_cell_id;
    }

    /**
     * <code>int64 s2_cell_id = 1;</code>
     */
    public function setS2CellId($var)
    {
        GPBUtil::checkInt64($var);
        $this->s2_cell_id = $var;
    }

    /**
     * <code>.POGOProtos.Map.Weather.DisplayWeather display_weather = 2;</code>
     */
    public function getDisplayWeather()
    {
        return $this->display_weather;
    }

    /**
     * <code>.POGOProtos.Map.Weather.DisplayWeather display_weather = 2;</code>
     */
    public function setDisplayWeather(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Map\Weather\DisplayWeather::class);
        $this->display_weather = $var;
    }

    /**
     * <code>.POGOProtos.Map.Weather.GameplayWeather gameplay_weather = 3;</code>
     */
    public function getGameplayWeather()
    {
        return $this->gameplay_weather;
    }

    /**
     * <code>.POGOProtos.Map.Weather.GameplayWeather gameplay_weather = 3;</code>
     */
    public function setGameplayWeather(&$var)
    {
        GPBUtil::checkMessage($var, \POGOProtos\Map\Weather\GameplayWeather::class);
        $this->gameplay_weather = $var;
    }

    /**
     * <code>repeated .POGOProtos.Map.Weather.WeatherAlert alerts = 4;</code>
     */
    public function getAlerts()
    {
        return $this->alerts;
    }

    /**
     * <code>repeated .POGOProtos.Map.Weather.WeatherAlert alerts = 4;</code>
     */
    public function setAlerts(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Map\Weather\WeatherAlert::class);
        $this->alerts = $var;
    }

}

