<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Map/Weather/DisplayWeather.proto

namespace POGOProtos\Map\Weather;

/**
 * Protobuf enum <code>POGOProtos.Map.Weather.DisplayWeather.DisplayLevel</code>
 */
class DisplayWeather_DisplayLevel
{
    /**
     * <code>LEVEL_0 = 0;</code>
     */
    const LEVEL_0 = 0;
    /**
     * <code>LEVEL_1 = 1;</code>
     */
    const LEVEL_1 = 1;
    /**
     * <code>LEVEL_2 = 2;</code>
     */
    const LEVEL_2 = 2;
    /**
     * <code>LEVEL_3 = 3;</code>
     */
    const LEVEL_3 = 3;
}

