<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/ChangeTeamMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class ChangeTeamMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Inventory\Item\ItemId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae9010a3f504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f4368616e67655465616d4d65737361" .
            "67652e70726f746f1227504f474f50726f746f732e4e6574776f726b696e" .
            "672e52657175657374732e4d6573736167657322750a114368616e676554" .
            "65616d4d657373616765122f0a046974656d18012001280e32212e504f47" .
            "4f50726f746f732e496e76656e746f72792e4974656d2e4974656d496412" .
            "2f0a047465616d18022001280e32212e504f474f50726f746f732e496e76" .
            "656e746f72792e4974656d2e4974656d4964620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

