<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/ConfirmPhotobombMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class ConfirmPhotobombMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa9010a45504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f436f6e6669726d50686f746f626f6d" .
            "624d6573736167652e70726f746f1227504f474f50726f746f732e4e6574" .
            "776f726b696e672e52657175657374732e4d65737361676573222f0a1743" .
            "6f6e6669726d50686f746f626f6d624d65737361676512140a0c656e636f" .
            "756e7465725f6964180120012806620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

