<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/DeclineSharedExRaidPassMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class DeclineSharedExRaidPassMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac5010a4c504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f4465636c696e655368617265644578" .
            "52616964506173734d6573736167652e70726f746f1227504f474f50726f" .
            "746f732e4e6574776f726b696e672e52657175657374732e4d6573736167" .
            "657322440a1e4465636c696e65536861726564457852616964506173734d" .
            "657373616765120f0a07666f72745f696418012001280912110a09726169" .
            "645f73656564180220012803620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

