<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/DownloadSettingsActionMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class DownloadSettingsActionMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad010a4b504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f446f776e6c6f616453657474696e67" .
            "73416374696f6e4d6573736167652e70726f746f1227504f474f50726f74" .
            "6f732e4e6574776f726b696e672e52657175657374732e4d657373616765" .
            "73222d0a1d446f776e6c6f616453657474696e6773416374696f6e4d6573" .
            "73616765120c0a0468617368180120012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

