<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/EquipBadgeMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class EquipBadgeMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\BadgeType::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab8010a3f504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f457175697042616467654d65737361" .
            "67652e70726f746f1227504f474f50726f746f732e4e6574776f726b696e" .
            "672e52657175657374732e4d6573736167657322440a1145717569704261" .
            "6467654d657373616765122f0a0a62616467655f7479706518012001280e" .
            "321b2e504f474f50726f746f732e456e756d732e42616467655479706562" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

