<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GenerateGmapSignedUrlMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class GenerateGmapSignedUrlMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7020a4a504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f47656e6572617465476d6170536967" .
            "6e656455726c4d6573736167652e70726f746f1227504f474f50726f746f" .
            "732e4e6574776f726b696e672e52657175657374732e4d65737361676573" .
            "22d7010a1c47656e6572617465476d61705369676e656455726c4d657373" .
            "61676512100a086c6174697475646518012001280112110a096c6f6e6769" .
            "74756465180220012801120d0a057769647468180320012805120e0a0668" .
            "6569676874180420012805120c0a047a6f6f6d18052001280512150a0d6c" .
            "616e67756167655f636f646518062001280912140a0c636f756e7472795f" .
            "636f646518072001280912110a096d61705f7374796c6518082001280912" .
            "100a086d61705f7479706518092001280912130a0b69636f6e5f70617261" .
            "6d73180a20012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

