<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetPhotobombMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class GetPhotobombMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8b010a41504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f47657450686f746f626f6d624d6573" .
            "736167652e70726f746f1227504f474f50726f746f732e4e6574776f726b" .
            "696e672e52657175657374732e4d6573736167657322150a134765745068" .
            "6f746f626f6d624d657373616765620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

