<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/GetWebTokenMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class GetWebTokenMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c010a40504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f476574576562546f6b656e4d657373" .
            "6167652e70726f746f1227504f474f50726f746f732e4e6574776f726b69" .
            "6e672e52657175657374732e4d6573736167657322270a12476574576562" .
            "546f6b656e4d65737361676512110a09636c69656e745f69641801200128" .
            "09620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

