<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/SetLobbyVisibilityMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class SetLobbyVisibilityMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acc010a47504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f5365744c6f6262795669736962696c" .
            "6974794d6573736167652e70726f746f1227504f474f50726f746f732e4e" .
            "6574776f726b696e672e52657175657374732e4d6573736167657322500a" .
            "195365744c6f6262795669736962696c6974794d65737361676512110a09" .
            "726169645f73656564180120012803120e0a0667796d5f69641802200128" .
            "0912100a086c6f6262795f6964180320032805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

