<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/UpdateNotificationMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class UpdateNotificationMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Enums\NotificationState::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad020a47504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f5570646174654e6f74696669636174" .
            "696f6e4d6573736167652e70726f746f1227504f474f50726f746f732e4e" .
            "6574776f726b696e672e52657175657374732e4d657373616765731a2850" .
            "4f474f50726f746f732f456e756d732f4e6f74696669636174696f6e5374" .
            "6174652e70726f746f2286010a195570646174654e6f7469666963617469" .
            "6f6e4d65737361676512180a106e6f74696669636174696f6e5f69647318" .
            "0120032809121b0a136372656174655f74696d657374616d705f6d731802" .
            "2003280312320a05737461746518032001280e32232e504f474f50726f74" .
            "6f732e456e756d732e4e6f74696669636174696f6e537461746562067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

