<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/UseItemMoveRerollMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class UseItemMoveRerollMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Inventory\Item\ItemId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afc010a46504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f5573654974656d4d6f76655265726f" .
            "6c6c4d6573736167652e70726f746f1227504f474f50726f746f732e4e65" .
            "74776f726b696e672e52657175657374732e4d657373616765732280010a" .
            "185573654974656d4d6f76655265726f6c6c4d65737361676512320a0769" .
            "74656d5f696418012001280e32212e504f474f50726f746f732e496e7665" .
            "6e746f72792e4974656d2e4974656d496412120a0a706f6b656d6f6e5f69" .
            "64180220012806121c0a147265726f6c6c5f756e6c6f636b65645f6d6f76" .
            "65180320012808620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

