<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/UseItemEncounterMessage.proto

namespace GPBMetadata\POGOProtos\Networking\Requests\Messages;

class UseItemEncounterMessage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\POGOProtos\Inventory\Item\ItemId::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af4010a45504f474f50726f746f732f4e6574776f726b696e672f526571" .
            "75657374732f4d657373616765732f5573654974656d456e636f756e7465" .
            "724d6573736167652e70726f746f1227504f474f50726f746f732e4e6574" .
            "776f726b696e672e52657175657374732e4d65737361676573227a0a1755" .
            "73654974656d456e636f756e7465724d657373616765122f0a046974656d" .
            "18012001280e32212e504f474f50726f746f732e496e76656e746f72792e" .
            "4974656d2e4974656d496412140a0c656e636f756e7465725f6964180220" .
            "01280612180a10737061776e5f706f696e745f6775696418032001280962" .
            "0670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

