<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/Quest.proto

namespace POGOProtos\Data\Quests;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Data\Quests\Quest\DailyCounter instead.
     * @deprecated
     */
    class Quest_DailyCounter {}
}
class_exists(Quest\DailyCounter::class);
@trigger_error('POGOProtos\Data\Quests\Quest_DailyCounter is deprecated and will be removed in the next major release. Use POGOProtos\Data\Quests\Quest\DailyCounter instead', E_USER_DEPRECATED);

