<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/QuestPokemonEncounter.proto

namespace POGOProtos\Data\Quests;

/**
 * Protobuf enum <code>POGOProtos.Data.Quests.QuestPokemonEncounter.EncounterType</code>
 */
class QuestPokemonEncounter_EncounterType
{
    /**
     * <code>SPAWN_POINT = 0;</code>
     */
    const SPAWN_POINT = 0;
    /**
     * <code>INCENSE = 1;</code>
     */
    const INCENSE = 1;
    /**
     * <code>DISK = 2;</code>
     */
    const DISK = 2;
    /**
     * <code>POST_RAID = 3;</code>
     */
    const POST_RAID = 3;
    /**
     * <code>STORY_QUEST = 4;</code>
     */
    const STORY_QUEST = 4;
    /**
     * <code>QUEST_STAMP_CARD = 5;</code>
     */
    const QUEST_STAMP_CARD = 5;
    /**
     * <code>CHALLENGE_QUEST = 6;</code>
     */
    const CHALLENGE_QUEST = 6;
}

