<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/QuestCondition.proto

namespace POGOProtos\Data\Quests;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Data\Quests\QuestCondition\WithWinRaidStatus instead.
     * @deprecated
     */
    class QuestCondition_WithWinRaidStatus {}
}
class_exists(QuestCondition\WithWinRaidStatus::class);
@trigger_error('POGOProtos\Data\Quests\QuestCondition_WithWinRaidStatus is deprecated and will be removed in the next major release. Use POGOProtos\Data\Quests\QuestCondition\WithWinRaidStatus instead', E_USER_DEPRECATED);

