<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/QuestStamp.proto

namespace POGOProtos\Data\Quests;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Data.Quests.QuestStamp</code>
 */
class QuestStamp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Quests.QuestStamp.Context context = 1;</code>
     */
    private $context = 0;
    /**
     * Generated from protobuf field <code>uint64 timestamp_ms = 2;</code>
     */
    private $timestamp_ms = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $context
     *     @type int|string $timestamp_ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Data\Quests\QuestStamp::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Quests.QuestStamp.Context context = 1;</code>
     * @return int
     */
    public function getContext()
    {
        return $this->context;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Data.Quests.QuestStamp.Context context = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setContext($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Data\Quests\QuestStamp_Context::class);
        $this->context = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp_ms = 2;</code>
     * @return int|string
     */
    public function getTimestampMs()
    {
        return $this->timestamp_ms;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp_ms = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestampMs($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp_ms = $var;

        return $this;
    }

}

