<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Quests/QuestCondition.proto

namespace POGOProtos\Data\Quests;

if (false) {
    /**
     * This class is deprecated. Use POGOProtos\Data\Quests\QuestCondition\WithCurveBall instead.
     * @deprecated
     */
    class QuestCondition_WithCurveBall {}
}
class_exists(QuestCondition\WithCurveBall::class);
@trigger_error('POGOProtos\Data\Quests\QuestCondition_WithCurveBall is deprecated and will be removed in the next major release. Use POGOProtos\Data\Quests\QuestCondition\WithCurveBall instead', E_USER_DEPRECATED);

