<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Data/Login/ListLoginAction.proto

namespace POGOProtos\Data\Login;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>POGOProtos.Data.Login.ListLoginActionResponse</code>
 */
class ListLoginActionResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>bool success = 1;</code>
     */
    private $success = false;
    /**
     * <code>repeated .POGOProtos.Data.Login.LoginDetail login_detail = 2;</code>
     */
    private $login_detail;

    public function __construct() {
        \GPBMetadata\POGOProtos\Data\Login\ListLoginAction::initOnce();
        parent::__construct();
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * <code>bool success = 1;</code>
     */
    public function setSuccess($var)
    {
        GPBUtil::checkBool($var);
        $this->success = $var;
    }

    /**
     * <code>repeated .POGOProtos.Data.Login.LoginDetail login_detail = 2;</code>
     */
    public function getLoginDetail()
    {
        return $this->login_detail;
    }

    /**
     * <code>repeated .POGOProtos.Data.Login.LoginDetail login_detail = 2;</code>
     */
    public function setLoginDetail(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \POGOProtos\Data\Login\LoginDetail::class);
        $this->login_detail = $var;
    }

}

