<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Settings/Master/Pokemon/EncounterAttributes.proto

namespace POGOProtos\Settings\Master\Pokemon;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>POGOProtos.Settings.Master.Pokemon.EncounterAttributes</code>
 */
class EncounterAttributes extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float base_capture_rate = 1;</code>
     */
    private $base_capture_rate = 0.0;
    /**
     * Generated from protobuf field <code>float base_flee_rate = 2;</code>
     */
    private $base_flee_rate = 0.0;
    /**
     * Generated from protobuf field <code>float collision_radius_m = 3;</code>
     */
    private $collision_radius_m = 0.0;
    /**
     * Generated from protobuf field <code>float collision_height_m = 4;</code>
     */
    private $collision_height_m = 0.0;
    /**
     * Generated from protobuf field <code>float collision_head_radius_m = 5;</code>
     */
    private $collision_head_radius_m = 0.0;
    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.PokemonMovementType movement_type = 6;</code>
     */
    private $movement_type = 0;
    /**
     * Generated from protobuf field <code>float movement_timer_s = 7;</code>
     */
    private $movement_timer_s = 0.0;
    /**
     * Generated from protobuf field <code>float jump_time_s = 8;</code>
     */
    private $jump_time_s = 0.0;
    /**
     * Generated from protobuf field <code>float attack_timer_s = 9;</code>
     */
    private $attack_timer_s = 0.0;
    /**
     * Generated from protobuf field <code>int32 bonus_candy_capture_reward = 10;</code>
     */
    private $bonus_candy_capture_reward = 0;
    /**
     * Generated from protobuf field <code>int32 bonus_stardust_capture_reward = 11;</code>
     */
    private $bonus_stardust_capture_reward = 0;
    /**
     * Generated from protobuf field <code>float attack_probability = 12;</code>
     */
    private $attack_probability = 0.0;
    /**
     * Generated from protobuf field <code>float dodge_probability = 13;</code>
     */
    private $dodge_probability = 0.0;
    /**
     * Generated from protobuf field <code>float dodge_duration_s = 14;</code>
     */
    private $dodge_duration_s = 0.0;
    /**
     * Generated from protobuf field <code>float dodge_distance = 15;</code>
     */
    private $dodge_distance = 0.0;
    /**
     * Generated from protobuf field <code>float camera_distance = 16;</code>
     */
    private $camera_distance = 0.0;
    /**
     * Generated from protobuf field <code>float min_pokemon_action_frequency_s = 17;</code>
     */
    private $min_pokemon_action_frequency_s = 0.0;
    /**
     * Generated from protobuf field <code>float max_pokemon_action_frequency_s = 18;</code>
     */
    private $max_pokemon_action_frequency_s = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $base_capture_rate
     *     @type float $base_flee_rate
     *     @type float $collision_radius_m
     *     @type float $collision_height_m
     *     @type float $collision_head_radius_m
     *     @type int $movement_type
     *     @type float $movement_timer_s
     *     @type float $jump_time_s
     *     @type float $attack_timer_s
     *     @type int $bonus_candy_capture_reward
     *     @type int $bonus_stardust_capture_reward
     *     @type float $attack_probability
     *     @type float $dodge_probability
     *     @type float $dodge_duration_s
     *     @type float $dodge_distance
     *     @type float $camera_distance
     *     @type float $min_pokemon_action_frequency_s
     *     @type float $max_pokemon_action_frequency_s
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\POGOProtos\Settings\Master\Pokemon\EncounterAttributes::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float base_capture_rate = 1;</code>
     * @return float
     */
    public function getBaseCaptureRate()
    {
        return $this->base_capture_rate;
    }

    /**
     * Generated from protobuf field <code>float base_capture_rate = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseCaptureRate($var)
    {
        GPBUtil::checkFloat($var);
        $this->base_capture_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float base_flee_rate = 2;</code>
     * @return float
     */
    public function getBaseFleeRate()
    {
        return $this->base_flee_rate;
    }

    /**
     * Generated from protobuf field <code>float base_flee_rate = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setBaseFleeRate($var)
    {
        GPBUtil::checkFloat($var);
        $this->base_flee_rate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float collision_radius_m = 3;</code>
     * @return float
     */
    public function getCollisionRadiusM()
    {
        return $this->collision_radius_m;
    }

    /**
     * Generated from protobuf field <code>float collision_radius_m = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setCollisionRadiusM($var)
    {
        GPBUtil::checkFloat($var);
        $this->collision_radius_m = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float collision_height_m = 4;</code>
     * @return float
     */
    public function getCollisionHeightM()
    {
        return $this->collision_height_m;
    }

    /**
     * Generated from protobuf field <code>float collision_height_m = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setCollisionHeightM($var)
    {
        GPBUtil::checkFloat($var);
        $this->collision_height_m = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float collision_head_radius_m = 5;</code>
     * @return float
     */
    public function getCollisionHeadRadiusM()
    {
        return $this->collision_head_radius_m;
    }

    /**
     * Generated from protobuf field <code>float collision_head_radius_m = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setCollisionHeadRadiusM($var)
    {
        GPBUtil::checkFloat($var);
        $this->collision_head_radius_m = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.PokemonMovementType movement_type = 6;</code>
     * @return int
     */
    public function getMovementType()
    {
        return $this->movement_type;
    }

    /**
     * Generated from protobuf field <code>.POGOProtos.Enums.PokemonMovementType movement_type = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMovementType($var)
    {
        GPBUtil::checkEnum($var, \POGOProtos\Enums\PokemonMovementType::class);
        $this->movement_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float movement_timer_s = 7;</code>
     * @return float
     */
    public function getMovementTimerS()
    {
        return $this->movement_timer_s;
    }

    /**
     * Generated from protobuf field <code>float movement_timer_s = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setMovementTimerS($var)
    {
        GPBUtil::checkFloat($var);
        $this->movement_timer_s = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float jump_time_s = 8;</code>
     * @return float
     */
    public function getJumpTimeS()
    {
        return $this->jump_time_s;
    }

    /**
     * Generated from protobuf field <code>float jump_time_s = 8;</code>
     * @param float $var
     * @return $this
     */
    public function setJumpTimeS($var)
    {
        GPBUtil::checkFloat($var);
        $this->jump_time_s = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float attack_timer_s = 9;</code>
     * @return float
     */
    public function getAttackTimerS()
    {
        return $this->attack_timer_s;
    }

    /**
     * Generated from protobuf field <code>float attack_timer_s = 9;</code>
     * @param float $var
     * @return $this
     */
    public function setAttackTimerS($var)
    {
        GPBUtil::checkFloat($var);
        $this->attack_timer_s = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 bonus_candy_capture_reward = 10;</code>
     * @return int
     */
    public function getBonusCandyCaptureReward()
    {
        return $this->bonus_candy_capture_reward;
    }

    /**
     * Generated from protobuf field <code>int32 bonus_candy_capture_reward = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setBonusCandyCaptureReward($var)
    {
        GPBUtil::checkInt32($var);
        $this->bonus_candy_capture_reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 bonus_stardust_capture_reward = 11;</code>
     * @return int
     */
    public function getBonusStardustCaptureReward()
    {
        return $this->bonus_stardust_capture_reward;
    }

    /**
     * Generated from protobuf field <code>int32 bonus_stardust_capture_reward = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setBonusStardustCaptureReward($var)
    {
        GPBUtil::checkInt32($var);
        $this->bonus_stardust_capture_reward = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float attack_probability = 12;</code>
     * @return float
     */
    public function getAttackProbability()
    {
        return $this->attack_probability;
    }

    /**
     * Generated from protobuf field <code>float attack_probability = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setAttackProbability($var)
    {
        GPBUtil::checkFloat($var);
        $this->attack_probability = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float dodge_probability = 13;</code>
     * @return float
     */
    public function getDodgeProbability()
    {
        return $this->dodge_probability;
    }

    /**
     * Generated from protobuf field <code>float dodge_probability = 13;</code>
     * @param float $var
     * @return $this
     */
    public function setDodgeProbability($var)
    {
        GPBUtil::checkFloat($var);
        $this->dodge_probability = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float dodge_duration_s = 14;</code>
     * @return float
     */
    public function getDodgeDurationS()
    {
        return $this->dodge_duration_s;
    }

    /**
     * Generated from protobuf field <code>float dodge_duration_s = 14;</code>
     * @param float $var
     * @return $this
     */
    public function setDodgeDurationS($var)
    {
        GPBUtil::checkFloat($var);
        $this->dodge_duration_s = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float dodge_distance = 15;</code>
     * @return float
     */
    public function getDodgeDistance()
    {
        return $this->dodge_distance;
    }

    /**
     * Generated from protobuf field <code>float dodge_distance = 15;</code>
     * @param float $var
     * @return $this
     */
    public function setDodgeDistance($var)
    {
        GPBUtil::checkFloat($var);
        $this->dodge_distance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float camera_distance = 16;</code>
     * @return float
     */
    public function getCameraDistance()
    {
        return $this->camera_distance;
    }

    /**
     * Generated from protobuf field <code>float camera_distance = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setCameraDistance($var)
    {
        GPBUtil::checkFloat($var);
        $this->camera_distance = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float min_pokemon_action_frequency_s = 17;</code>
     * @return float
     */
    public function getMinPokemonActionFrequencyS()
    {
        return $this->min_pokemon_action_frequency_s;
    }

    /**
     * Generated from protobuf field <code>float min_pokemon_action_frequency_s = 17;</code>
     * @param float $var
     * @return $this
     */
    public function setMinPokemonActionFrequencyS($var)
    {
        GPBUtil::checkFloat($var);
        $this->min_pokemon_action_frequency_s = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float max_pokemon_action_frequency_s = 18;</code>
     * @return float
     */
    public function getMaxPokemonActionFrequencyS()
    {
        return $this->max_pokemon_action_frequency_s;
    }

    /**
     * Generated from protobuf field <code>float max_pokemon_action_frequency_s = 18;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxPokemonActionFrequencyS($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_pokemon_action_frequency_s = $var;

        return $this;
    }

}

