<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POGOProtos/Networking/Requests/Messages/UpdatePlayerLocationMessage.proto

namespace POGOProtos\Networking\Requests\Messages\UpdatePlayerLocationMessage;

/**
 * Protobuf type <code>POGOProtos.Networking.Requests.Messages.UpdatePlayerLocationMessage.PingReason</code>
 */
class PingReason
{
    /**
     * Generated from protobuf enum <code>UNSET = 0;</code>
     */
    const PBUNSET = 0;
    /**
     * Generated from protobuf enum <code>ENTRANCE_EVENT = 1;</code>
     */
    const ENTRANCE_EVENT = 1;
    /**
     * Generated from protobuf enum <code>EXIT_EVENT = 2;</code>
     */
    const EXIT_EVENT = 2;
    /**
     * Generated from protobuf enum <code>DWELL_EVENT = 3;</code>
     */
    const DWELL_EVENT = 3;
    /**
     * Generated from protobuf enum <code>VISIT_EVENT = 4;</code>
     */
    const VISIT_EVENT = 4;
    /**
     * Generated from protobuf enum <code>FITNESS_WAKEUP = 5;</code>
     */
    const FITNESS_WAKEUP = 5;
    /**
     * Generated from protobuf enum <code>OTHER_WAKEUP = 6;</code>
     */
    const OTHER_WAKEUP = 6;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PingReason::class, \POGOProtos\Networking\Requests\Messages\UpdatePlayerLocationMessage_PingReason::class);

